using System.Text.RegularExpressions;
using Chummer.Run.Api.Services;
using Xunit;

namespace Chummer.Tests;

public sealed partial class PublicFrontDoorCopyPolishTests
{
    [Theory]
    [InlineData("Landing.cshtml")]
    [InlineData("Downloads.cshtml")]
    [InlineData("Status.cshtml")]
    [InlineData("ProductStory.cshtml")]
    public void Public_front_door_views_avoid_internal_ai_and_proof_language(string viewName)
    {
        string view = File.ReadAllText(RepoPaths.FromRoot("Chummer.Run.Api", "Views", "PublicLanding", viewName));
        string visibleText = ExtractVisibleText(view);

        Assert.DoesNotMatch(StandaloneAiRegex(), visibleText);
        foreach (string marker in ForbiddenVisibleMarkers)
        {
            Assert.DoesNotContain(marker, visibleText, StringComparison.OrdinalIgnoreCase);
        }
    }

    [Fact]
    public void Public_landing_manifest_keeps_black_ledger_out_of_first_impression_copy()
    {
        string manifest = File.ReadAllText(RepoPaths.FromRoot(".codex-design", "product", "PUBLIC_LANDING_MANIFEST.yaml"));
        string firstImpression = string.Join(Environment.NewLine, manifest.Split('\n').Take(80));

        Assert.DoesNotContain("Black Ledger", firstImpression, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("Real product proof", firstImpression, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("Projection compiled", firstImpression, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("Download Chummer", firstImpression, StringComparison.Ordinal);
    }

    [Fact]
    public void Shared_layout_runs_public_copy_humanizer_without_touching_code_blocks()
    {
        string layout = File.ReadAllText(RepoPaths.FromRoot("Chummer.Run.Api", "Views", "Shared", "_Layout.cshtml"));
        string script = File.ReadAllText(RepoPaths.FromRoot("Chummer.Run.Api", "wwwroot", "js", "public-copy-humanizer.js"));

        Assert.Contains("public-copy-humanizer.js", layout, StringComparison.Ordinal);
        Assert.Contains("SHOW_TEXT", script, StringComparison.Ordinal);
        Assert.Contains("tagName === \"CODE\"", script, StringComparison.Ordinal);
        Assert.Contains("tagName === \"PRE\"", script, StringComparison.Ordinal);
        Assert.Contains(@"\bAI\b", script, StringComparison.Ordinal);
        Assert.Contains(@"\bBlack Ledger\b", script, StringComparison.Ordinal);
        Assert.Contains(@"\bproof\b", script, StringComparison.Ordinal);
        Assert.Contains(@"\breceipt\b", script, StringComparison.Ordinal);
        Assert.Contains(@"\bprovider\b", script, StringComparison.Ordinal);
    }

    [Fact]
    public void Public_copy_humanizer_removes_internal_release_vocabulary()
    {
        string cleaned = PublicFacingCopyHumanizer.Clean("ALICE generated an AI proof receipt for the Black Ledger operator lane.");

        Assert.Equal("Alice created a check for the campaign city user path.", cleaned);
        Assert.DoesNotContain("AI", cleaned, StringComparison.Ordinal);
        Assert.DoesNotContain("assistant", cleaned, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Auth_entry_avoids_internal_install_link_language()
    {
        string view = File.ReadAllText(RepoPaths.FromRoot("Chummer.Run.Api", "Views", "Auth", "Entry.cshtml"));
        string visibleText = ExtractVisibleText(view);

        Assert.DoesNotContain("handoff", visibleText, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("callback", visibleText, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("Keep this install attached to your account.", visibleText, StringComparison.Ordinal);
    }

    private static readonly string[] ForbiddenVisibleMarkers =
    [
        "generated by AI",
        "proof",
        "receipt",
        "operator",
        "grounded",
        "governed",
        "source packet",
        "Black Ledger",
        "Starter lane",
        "world lanes",
        "account-assisted install"
    ];

    private static string ExtractVisibleText(string view)
    {
        string withoutCode = RazorTopCodeBlockRegex().Replace(view, " ");
        withoutCode = RazorFunctionsBlockRegex().Replace(withoutCode, " ");
        var textNodes = HtmlTextNodeRegex()
            .Matches(withoutCode)
            .Select(static match => RazorExpressionRegex().Replace(match.Groups[1].Value, " "))
            .Where(static text => !string.IsNullOrWhiteSpace(text))
            .Where(static text => !text.Contains('{', StringComparison.Ordinal)
                && !text.Contains('}', StringComparison.Ordinal)
                && !text.Contains(';', StringComparison.Ordinal)
                && !text.Contains(" var ", StringComparison.Ordinal));
        return WhitespaceRegex().Replace(string.Join(" ", textNodes), " ").Trim();
    }

    [GeneratedRegex(@"@\{[\s\S]*?\n\}\s*(?=<)", RegexOptions.CultureInvariant)]
    private static partial Regex RazorTopCodeBlockRegex();

    [GeneratedRegex(@"^@functions\s*\{[\s\S]*?^\}\s*(?=<)", RegexOptions.Multiline | RegexOptions.CultureInvariant)]
    private static partial Regex RazorFunctionsBlockRegex();

    [GeneratedRegex(@">([^<]+)<", RegexOptions.CultureInvariant)]
    private static partial Regex HtmlTextNodeRegex();

    [GeneratedRegex(@"@\(?[A-Za-z0-9_\.]+[^ \t\r\n<]*\)?", RegexOptions.CultureInvariant)]
    private static partial Regex RazorExpressionRegex();

    [GeneratedRegex(@"\bAI\b", RegexOptions.CultureInvariant)]
    private static partial Regex StandaloneAiRegex();

    [GeneratedRegex(@"\s+", RegexOptions.CultureInvariant)]
    private static partial Regex WhitespaceRegex();
}
