using System.Text.RegularExpressions;

namespace Chummer.Run.Api.Services;

public static partial class PublicFacingCopyHumanizer
{
    private static readonly (string From, string To)[] Replacements =
    [
        ("ALICE", "Alice"),
        ("Black Ledger", "campaign city"),
        ("proof receipt", "check"),
        ("generated by AI", "created"),
        ("AI-generated", "created"),
        ("AI generated", "created"),
        ("generated", "created"),
        ("Unmixr AI", "Unmixr"),
        ("source packet", "source"),
        ("provider", "service"),
        ("LTD", "tool"),
        ("proof trail", "checks"),
        ("proof", "check"),
        ("receipt", "check"),
        ("operator lane", "user path"),
        ("operator-facing", "private"),
        ("operator view", "account view"),
        ("starter lane", "starter path"),
    ];

    public static string Clean(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return string.Empty;
        }

        string cleaned = value.Trim();
        foreach ((string from, string to) in Replacements)
        {
            cleaned = cleaned.Replace(from, to, StringComparison.OrdinalIgnoreCase);
        }

        cleaned = ArticleAiRegex().Replace(cleaned, "a");
        cleaned = StandaloneAiRegex().Replace(cleaned, "help");
        cleaned = DuplicateWhitespaceRegex().Replace(cleaned, " ");
        cleaned = SpaceBeforePunctuationRegex().Replace(cleaned, "$1");
        return cleaned.Trim();
    }

    public static IReadOnlyList<string> CleanLines(IEnumerable<string>? values)
        => values?
            .Select(Clean)
            .Where(static value => !string.IsNullOrWhiteSpace(value))
            .ToArray()
           ?? Array.Empty<string>();

    [GeneratedRegex(@"\s+", RegexOptions.CultureInvariant)]
    private static partial Regex DuplicateWhitespaceRegex();

    [GeneratedRegex(@"\s+([.,;:!?])", RegexOptions.CultureInvariant)]
    private static partial Regex SpaceBeforePunctuationRegex();

    [GeneratedRegex(@"\bAI\b", RegexOptions.CultureInvariant)]
    private static partial Regex StandaloneAiRegex();

    [GeneratedRegex(@"\ban\s+AI\b", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex ArticleAiRegex();
}
