using System.Text.RegularExpressions;

namespace Chummer.Run.Api.Services;

public static partial class PublicFacingCopyHumanizer
{
    private static readonly (string From, string To)[] Replacements =
    [
        ("Public Proof Shelf", "Public Files"),
        ("Proof Shelf", "Files"),
        ("Rule Environment Studio", "Rules Setup"),
        ("Rule-environment studio", "Rules setup"),
        ("rule-environment", "rules setup"),
        ("Before-after diffs", "Changes"),
        ("Explain receipts", "Explanations"),
        ("Explain receipt", "Explanation"),
        ("AI assistant", "help"),
        ("ALICE", "help"),
        ("Alice", "help"),
        ("assistant", "help"),
        ("Black Ledger", "campaign city"),
        ("proof receipt", "update"),
        ("generated by AI", "made"),
        ("AI-generated", "made"),
        ("AI generated", "made"),
        ("generated", "prepared"),
        ("Unmixr AI", "Unmixr"),
        ("source packet", "source"),
        ("provider-backed", "built-in"),
        ("provider", "service"),
        ("artifacts", "files"),
        ("artifact", "file"),
        ("LTD", "tool"),
        ("proof trail", "details"),
        ("proof page", "details"),
        ("current proof", "current status"),
        ("live proof", "live status"),
        ("JSON packet", "details"),
        ("command posture", "command state"),
        ("readiness posture", "readiness"),
        ("release truth", "release status"),
        ("registry-backed truth", "current records"),
        ("registry truth", "current records"),
        ("registry", "records"),
        ("source of truth", "source"),
        ("evidence drawer", "details"),
        ("evidence", "details"),
        ("proofs", "details"),
        ("proof", "status"),
        ("receipts", "updates"),
        ("receipt", "update"),
        ("verification", "confirmation"),
        ("verified", "confirmed"),
        ("validated", "reviewed"),
        ("validation", "review"),
        ("quality checklist", "quality list"),
        ("checklist", "list"),
        ("governed", "reviewed"),
        ("grounded", "clear"),
        ("audit", "review"),
        ("audits", "reviews"),
        ("verdict", "status"),
        ("verified validation checks", "review"),
        ("validation checks", "review"),
        ("checks", "details"),
        ("check", "detail"),
        ("trust posture", "status"),
        ("support posture", "support status"),
        ("release posture", "release status"),
        ("posture", "status"),
        ("operator lane", "workspace"),
        ("operators", "maintainers"),
        ("operator", "maintainer"),
        ("campaign city workspace", "campaign city"),
        ("workspace path", "workspace"),
        ("claim tickets", "pending claims"),
        ("claim ticket", "pending claim"),
        ("install ticket", "claim link"),
        ("continuation rail", "return path"),
        ("return rail", "return path"),
        ("release rail", "release path"),
        ("install rail", "linked copy"),
        ("rail", "path"),
        ("lane", "path"),
        ("shelf", "page"),
        ("operator-facing", "private"),
        ("operator view", "account view"),
        ("starter-lane", "starter path"),
        ("starter lane", "starter path"),
        ("assistants", "help"),
        ("horizon brief", "maintenance note"),
        ("horizon detail", "maintenance note"),
        ("horizon page", "maintenance page"),
        ("horizon-only", "private"),
        ("horizons", "maintenance"),
        ("horizon", "maintenance"),
    ];

    public static string Clean(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return string.Empty;
        }

        string cleaned = value.Trim();
        foreach ((string from, string to) in Replacements)
        {
            cleaned = ReplacePhrase(cleaned, from, to);
        }

        cleaned = ArticleAiRegex().Replace(cleaned, "a");
        cleaned = StandaloneAiRegex().Replace(cleaned, "help");
        cleaned = ArticleHelpRegex().Replace(cleaned, "help");
        cleaned = ArticleConsonantReplacementRegex().Replace(cleaned, "a $1");
        cleaned = AUpdateRegex().Replace(cleaned, "an update");
        cleaned = ReviewPassedRegex().Replace(cleaned, "The return path is ready.");
        cleaned = HelpPreparedStatusRegex().Replace(cleaned, "help prepared an update");
        cleaned = HelpPreparedUpdateForRegex().Replace(cleaned, "An update is ready for $1.");
        cleaned = DuplicateWhitespaceRegex().Replace(cleaned, " ");
        cleaned = SpaceBeforePunctuationRegex().Replace(cleaned, "$1");
        cleaned = cleaned.Trim();

        char originalFirst = value.Trim()[0];
        if (char.IsUpper(originalFirst) && cleaned.Length > 0 && char.IsLower(cleaned[0]))
        {
            cleaned = char.ToUpperInvariant(cleaned[0]) + cleaned[1..];
        }

        return cleaned;
    }

    private static string ReplacePhrase(string value, string from, string to)
    {
        string pattern = $@"(?<![A-Za-z0-9]){Regex.Escape(from)}(?![A-Za-z0-9])";
        return Regex.Replace(value, pattern, to, RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
    }

    public static IReadOnlyList<string> CleanLines(IEnumerable<string>? values)
        => values?
            .Select(Clean)
            .Where(static value => !string.IsNullOrWhiteSpace(value))
            .ToArray()
           ?? Array.Empty<string>();

    [GeneratedRegex(@"\s+", RegexOptions.CultureInvariant)]
    private static partial Regex DuplicateWhitespaceRegex();

    [GeneratedRegex(@"\s+([.,;:!?])", RegexOptions.CultureInvariant)]
    private static partial Regex SpaceBeforePunctuationRegex();

    [GeneratedRegex(@"\bAI\b", RegexOptions.CultureInvariant)]
    private static partial Regex StandaloneAiRegex();

    [GeneratedRegex(@"\ban\s+AI\b", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex ArticleAiRegex();

    [GeneratedRegex(@"\b(?:an|a)\s+help\b", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex ArticleHelpRegex();

    [GeneratedRegex(@"\ban\s+(linked|path|status|record|update|file|service|source|page|tool|roadmap|review|confirmation|Chummer)\b", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex ArticleConsonantReplacementRegex();

    [GeneratedRegex(@"\b(?:a|an)\s+review(?:\s+status)?\s+says\s+(?:confirmed\s+)?review(?:\s+details)?\s+passed\s+on\s+the\s+return\s+path\.?", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex ReviewPassedRegex();

    [GeneratedRegex(@"\bhelp\s+prepared\s+(?:a\s+)?status\b", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex HelpPreparedStatusRegex();

    [GeneratedRegex(@"\bhelp\s+prepared\s+an?\s+update\s+for\s+(.+?)\.?$", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex HelpPreparedUpdateForRegex();

    [GeneratedRegex(@"\ba\s+update\b", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex AUpdateRegex();
}
