using System.Collections.Concurrent;
using System.Text.RegularExpressions;

namespace Chummer.Run.Api.Services;

public static partial class PublicFacingCopyHumanizer
{
    private const int MaxCachedInputLength = 4096;
    private const int MaxCleanCacheEntries = 4096;
    private static readonly TimeSpan RegexTimeout = TimeSpan.FromMilliseconds(50);
    private static readonly ConcurrentDictionary<string, string> CleanCache = new(StringComparer.Ordinal);
    private static readonly (string From, string To)[] Replacements =
    [
        ("Public Proof Shelf", "Public Files"),
        ("Proof Shelf", "Files"),
        ("Product Governor", "product decision"),
        ("proof-bound", "status-based"),
        ("proof bound", "status-based"),
        ("receipt-bound", "record-based"),
        ("receipt bound", "record-based"),
        ("release-backed", "release-based"),
        ("release backed", "release-based"),
        ("registry-backed", "record-based"),
        ("registry backed", "record-based"),
        ("package truth", "package status"),
        ("governor truth", "decision status"),
        ("micro-proof", "status note"),
        ("micro proof", "status note"),
        ("Rule Environment Studio", "Rules Setup"),
        ("Rule-environment studio", "Rules setup"),
        ("rule-environment", "rules setup"),
        ("Before-after diffs", "Changes"),
        ("Explain receipts", "Explanations"),
        ("Explain receipt", "Explanation"),
        ("AI assistant", "help"),
        ("ALICE", "help"),
        ("Alice", "help"),
        ("assistant", "help"),
        ("Black Ledger", "campaign city"),
        ("proof receipt", "update"),
        ("proof receipts", "details"),
        ("summary data", "details"),
        ("conversation data", "conversation details"),
        ("recent action receipts", "recent activity"),
        ("provenance receipts", "history"),
        ("provenance recovery receipts", "recovery history"),
        ("conflict receipts", "conflicts"),
        ("generated by AI", "made"),
        ("AI-generated", "made"),
        ("AI generated", "made"),
        ("generated", "prepared"),
        ("Unmixr AI", "Unmixr"),
        ("source packet", "source"),
        ("source-bound", "source-based"),
        ("source bound", "source-based"),
        ("provider-backed", "built-in"),
        ("provider", "service"),
        ("provenance", "source"),
        ("authority", "source"),
        ("audit summary", "review"),
        ("audit posture", "status"),
        ("bounded failure", "not ready"),
        ("bounded-failure", "not ready"),
        ("bounded review", "limited review"),
        ("deterministic", "consistent"),
        ("runtime", "app"),
        ("artifact factory", "file builder"),
        ("publication lane", "publishing path"),
        ("publication rail", "publishing path"),
        ("provider state", "service status"),
        ("governor", "guide"),
        ("artifacts", "files"),
        ("artifact", "file"),
        ("LTD", "tool"),
        ("proof trail", "details"),
        ("proof page", "details"),
        ("current proof", "current status"),
        ("live proof", "live status"),
        ("world authority", "world changes"),
        ("autonomous simulation", "automatic simulation"),
        ("JSON packet", "details"),
        ("command posture", "command state"),
        ("readiness posture", "readiness"),
        ("release truth", "release status"),
        ("registry-backed truth", "current records"),
        ("registry truth", "current records"),
        ("registry", "records"),
        ("source of truth", "source"),
        ("truth", "status"),
        ("canonized", "ready"),
        ("canonical", "standard"),
        ("canon", "source"),
        ("evidence drawer", "details"),
        ("evidence", "details"),
        ("proofs", "details"),
        ("proof", "status"),
        ("receipts", "records"),
        ("receipt", "record"),
        ("verification", "confirmation"),
        ("verified", "confirmed"),
        ("validated", "checked"),
        ("verified validation checks", "review"),
        ("validation checks", "review"),
        ("validation", "check"),
        ("quality checklist", "quality list"),
        ("checklist", "list"),
        ("governed", string.Empty),
        ("grounded", "clear"),
        ("audit", "review"),
        ("audits", "reviews"),
        ("verdict", "status"),
        ("checks passed", "ready"),
        ("check passed", "ready"),
        ("checks", "details"),
        ("check", "detail"),
        ("trust posture", "status"),
        ("support posture", "support status"),
        ("release posture", "release status"),
        ("posture", "status"),
        ("operator lane", "workspace"),
        ("operators", "maintainers"),
        ("operator", "maintainer"),
        ("campaign city workspace", "campaign city"),
        ("workspace path", "workspace"),
        ("claim tickets", "pending claims"),
        ("claim ticket", "pending claim"),
        ("install ticket", "claim link"),
        ("handoff codes", "access codes"),
        ("handoff code", "access code"),
        ("handoffs", "next steps"),
        ("handoff", "next step"),
        ("first-party rails", "Chummer paths"),
        ("first-party rail", "Chummer path"),
        ("first-party", "Chummer"),
        ("typed GM-control APIs", "working GM-control support"),
        ("typed starter/recovery APIs", "working starter/recovery support"),
        ("typed edition-head APIs", "working edition support"),
        ("typed jump-target APIs", "working jump support"),
        ("typed jump APIs", "working jump support"),
        ("typed capability/policy APIs", "working capability controls"),
        ("typed publication page", "publication page"),
        ("typed workspace and run support", "workspace and run support"),
        ("open-run orchestration APIs", "open-run support"),
        ("command rail", "command path"),
        ("continuity rail", "continuity path"),
        ("aftermath rail", "aftermath path"),
        ("trust rail", "trust path"),
        ("continuation rail", "return path"),
        ("return rail", "return path"),
        ("release rail", "release path"),
        ("install rail", "linked copy"),
        ("rail", "path"),
        ("lane", "path"),
        ("shelf", "page"),
        ("bounded", "limited"),
        ("operator-facing", "private"),
        ("operator view", "account view"),
        ("starter-lane", "starter path"),
        ("starter lane", "starter path"),
        ("assistants", "help"),
        ("horizon brief", "maintenance note"),
        ("horizon detail", "maintenance note"),
        ("horizon page", "maintenance page"),
        ("horizon-only", "private"),
        ("horizons", "maintenance"),
        ("horizon", "maintenance"),
    ];
    private static readonly (Regex Pattern, string To)[] ReplacementRules = Replacements
        .Select(static replacement => (
            new Regex(
                BuildPhrasePattern(replacement.From),
                RegexOptions.IgnoreCase | RegexOptions.CultureInvariant,
                RegexTimeout),
            replacement.To))
        .ToArray();

    public static string Clean(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return string.Empty;
        }

        string cacheKey = value.Trim();
        if (cacheKey.Length <= MaxCachedInputLength && CleanCache.TryGetValue(cacheKey, out string? cached))
        {
            return cached;
        }

        string cleaned = cacheKey;
        foreach ((Regex pattern, string to) in ReplacementRules)
        {
            cleaned = pattern.Replace(cleaned, to);
        }

        cleaned = ArticleAiRegex().Replace(cleaned, "a");
        cleaned = StandaloneAiRegex().Replace(cleaned, "help");
        cleaned = ArticleHelpRegex().Replace(cleaned, "help");
        cleaned = ArticleConsonantReplacementRegex().Replace(cleaned, "a $1");
        cleaned = AUpdateRegex().Replace(cleaned, "an update");
        cleaned = ReviewPassedRegex().Replace(cleaned, "The return path is ready.");
        cleaned = HelpPreparedStatusRegex().Replace(cleaned, "help prepared an update");
        cleaned = HelpPreparedUpdateForRegex().Replace(cleaned, "An update is ready for $1.");
        cleaned = ServiceDetailReadyRegex().Replace(cleaned, "service ready");
        cleaned = ServiceReviewPassedRegex().Replace(cleaned, "service ready");
        cleaned = DetailsIsRegex().Replace(cleaned, "$1details are");
        cleaned = ReviewDetailsRegex().Replace(cleaned, "review");
        cleaned = DuplicateWhitespaceRegex().Replace(cleaned, " ");
        cleaned = SpaceBeforePunctuationRegex().Replace(cleaned, "$1");
        cleaned = cleaned.Trim();

        char originalFirst = cacheKey[0];
        if (char.IsUpper(originalFirst) && cleaned.Length > 0 && char.IsLower(cleaned[0]))
        {
            cleaned = char.ToUpperInvariant(cleaned[0]) + cleaned[1..];
        }

        if (cacheKey.Length <= MaxCachedInputLength && CleanCache.Count < MaxCleanCacheEntries)
        {
            CleanCache.TryAdd(cacheKey, cleaned);
        }

        return cleaned;
    }

    private static string BuildPhrasePattern(string from)
        => $@"(?<![A-Za-z0-9]){Regex.Escape(from)}(?![A-Za-z0-9])";

    public static IReadOnlyList<string> CleanLines(IEnumerable<string>? values)
        => values?
            .Select(Clean)
            .Where(static value => !string.IsNullOrWhiteSpace(value))
            .ToArray()
           ?? Array.Empty<string>();

    [GeneratedRegex(@"\s+", RegexOptions.CultureInvariant)]
    private static partial Regex DuplicateWhitespaceRegex();

    [GeneratedRegex(@"\s+([.,;:!?])", RegexOptions.CultureInvariant)]
    private static partial Regex SpaceBeforePunctuationRegex();

    [GeneratedRegex(@"\bAI\b", RegexOptions.CultureInvariant)]
    private static partial Regex StandaloneAiRegex();

    [GeneratedRegex(@"\ban\s+AI\b", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex ArticleAiRegex();

    [GeneratedRegex(@"\b(?:an|a)\s+help\b", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex ArticleHelpRegex();

    [GeneratedRegex(@"\ban\s+(linked|path|status|record|update|file|service|source|page|tool|roadmap|review|confirmation|Chummer)\b", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex ArticleConsonantReplacementRegex();

    [GeneratedRegex(@"\b(?:a|an)\s+review(?:\s+status)?\s+says\s+(?:confirmed\s+)?(?:review|check|detail)(?:\s+details?)?\s+(?:passed|ready)\s+on\s+the\s+return\s+path\.?", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex ReviewPassedRegex();

    [GeneratedRegex(@"\bhelp\s+prepared\s+(?:a\s+)?status\b", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex HelpPreparedStatusRegex();

    [GeneratedRegex(@"\bhelp\s+prepared\s+an?\s+update\s+for\s+(.+?)\.?$", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex HelpPreparedUpdateForRegex();

    [GeneratedRegex(@"\ba\s+update\b", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex AUpdateRegex();

    [GeneratedRegex(@"\b(The\s+|the\s+)?details\s+is\b", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex DetailsIsRegex();

    [GeneratedRegex(@"\bservice\s+details?\s+ready\b", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex ServiceDetailReadyRegex();

    [GeneratedRegex(@"\bservice\s+review\s+passed\b", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex ServiceReviewPassedRegex();

    [GeneratedRegex(@"\breview\s+details\b", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant)]
    private static partial Regex ReviewDetailsRegex();
}
