import { readFileSync } from 'node:fs';
import path from 'node:path';
import { test, expect } from 'playwright/test';

const repoRoot = process.cwd();
const landingViewPath = path.join(repoRoot, 'Chummer.Run.Api', 'Views', 'PublicLanding', 'Landing.cshtml');

test('landing implements the product-first homepage structure', async () => {
  const view = readFileSync(landingViewPath, 'utf8');

  expect(view).toContain('A Shadowrun character manager for clean sheets and faster tables.');
  expect(view).toContain('Download Chummer');
  expect(view).toContain('data-homepage-section="hero"');
  expect(view).toContain('@publicPlatformSummary');
  expect(view).toContain('>Help</a>');
  expect(view).toContain('>Build</button>');
  expect(view).toContain('>Play</button>');
  expect(view).toContain('Sign in first');
  expect(view).toContain('minimal-hero__visual--preview');
  expect(view).not.toContain('minimal-runner-rail');
  expect(view).not.toContain('/media/promo/every-wonder-horizon-promo.mp4');
  expect(view).not.toContain('The city is moving.');
  expect(view).not.toContain('Open Black Ledger');
  expect(view).not.toContain('generated by AI');
  expect(view).not.toContain('proof');
});
