import { readFileSync } from 'node:fs';
import path from 'node:path';
import { test, expect } from 'playwright/test';

const repoRoot = process.cwd();
const landingViewPath = path.join(repoRoot, 'Chummer.Run.Api', 'Views', 'PublicLanding', 'Landing.cshtml');

test('landing implements the product-first homepage structure', async () => {
  const view = readFileSync(landingViewPath, 'utf8');

  expect(view).toContain('Build and maintain Shadowrun characters without losing the details between sessions.');
  expect(view).toContain('For Shadowrun');
  expect(view).toContain('Stable</a>');
  expect(view).toContain('Nightly</a>');
  expect(view).toContain('data-homepage-section="hero"');
  expect(view).toContain('Status</a>');
  expect(view).toContain('minimal-hero__visual--screenshot');
  expect(view).not.toContain('The city is moving.');
  expect(view).not.toContain('Open Black Ledger');
  expect(view).not.toContain('generated by AI');
  expect(view).not.toContain('proof');
});
