import { readFileSync } from 'node:fs';
import path from 'node:path';
import { test, expect } from 'playwright/test';

const repoRoot = process.cwd();
const publicLandingViews = [
  'Landing.cshtml',
  'Downloads.cshtml',
  'ProductStory.cshtml',
  'Horizons.cshtml',
].map(file => path.join(repoRoot, 'Chummer.Run.Api', 'Views', 'PublicLanding', file));

test('front-door copy stays minimal, human, and product-first', async () => {
  const views = publicLandingViews.map(file => readFileSync(file, 'utf8')).join('\n');

  expect(views).toContain('Build and maintain Shadowrun characters without losing the details between sessions.');
  expect(views).toContain('Choose Stable or Nightly.');
  expect(views).toContain('Not the front door');
  expect(views).toContain('Future work stays behind the main app.');

  const blockedPhrases = [
    'generated by AI',
    'AI-generated',
    'MagicFit',
    'Unmixr',
    'JoggAI',
    'Subscribr',
    'Open Black Ledger',
    'The city is moving.',
    'Signed-in download',
    'Keep this install linked',
    'short-lived install ticket',
    'proof language',
  ];

  for (const phrase of blockedPhrases) {
    expect(views, `front-door copy leaked "${phrase}"`).not.toContain(phrase);
  }
});
