<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Reference Include="Chummer.Play.Contracts">
      <HintPath>..\Chummer.Play.Contracts\bin\$(Configuration)\net10.0\Chummer.Play.Contracts.dll</HintPath>
    </Reference>
    <Reference Include="Chummer.Media.Contracts">
      <HintPath>..\Chummer.Media.Contracts\bin\$(Configuration)\net10.0\Chummer.Media.Contracts.dll</HintPath>
    </Reference>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
