from __future__ import annotations

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]


def read(relative_path: str) -> str:
    return (REPO_ROOT / relative_path).read_text(encoding="utf-8")


def test_main_public_routes_use_minimal_surface_contract() -> None:
    landing = read("Chummer.Run.Api/Views/PublicLanding/Landing.cshtml")
    downloads = read("Chummer.Run.Api/Views/PublicLanding/Downloads.cshtml")
    status = read("Chummer.Run.Api/Views/PublicLanding/Status.cshtml")
    horizons = read("Chummer.Run.Api/Views/PublicLanding/Horizons.cshtml")
    product_story = read("Chummer.Run.Api/Views/PublicLanding/ProductStory.cshtml")
    faq = read("Chummer.Run.Api/Views/PublicLanding/Faq.cshtml")
    trust_page = read("Chummer.Run.Api/Views/PublicLanding/TrustPage.cshtml")

    for source in (landing, downloads, status, horizons, product_story, faq):
        assert 'surface-minimal' in source

    assert 'surface-help surface-minimal' in trust_page
    assert 'minimal-help-grid' in trust_page
    assert 'minimal-help-card' in trust_page
    assert 'Pick one path' in trust_page


def test_public_front_door_hides_unready_campaign_and_ai_language() -> None:
    landing = read("Chummer.Run.Api/Views/PublicLanding/Landing.cshtml")
    horizons = read("Chummer.Run.Api/Views/PublicLanding/Horizons.cshtml")
    product_story = read("Chummer.Run.Api/Views/PublicLanding/ProductStory.cshtml")

    for source in (landing, horizons, product_story):
        assert "Black Ledger" not in source
        assert "generated by AI" not in source
        assert "AI-generated" not in source
        assert "proof receipt" not in source
        assert "artifact-gallery" not in source

    assert "Not the front door" in horizons
    assert "Downloads first" in horizons


def test_homepage_has_minimal_product_video_surface() -> None:
    landing = read("Chummer.Run.Api/Views/PublicLanding/Landing.cshtml")
    site_css = read("Chummer.Run.Api/wwwroot/css/site.css")

    assert 'class="minimal-video"' in landing
    assert 'aria-label="Product video"' in landing
    assert "/media/promo/chummer6-flagship-promo.mp4" in landing
    assert "/media/promo/chummer6-flagship-promo.webm" in landing
    assert "/media/promo/chummer6-flagship-promo.vtt" in landing
    assert ".minimal-video" in site_css
    assert "aspect-ratio: 16 / 9;" in site_css

    for forbidden in (
        "proof",
        "receipt",
        "artifact",
        "generated by AI",
        "AI-generated",
    ):
        assert forbidden not in landing


def test_participation_surface_uses_plain_character_helper_copy() -> None:
    participate = read("Chummer.Run.Api/Views/PublicLanding/Participate.cshtml")

    assert "Character help preview" in participate
    assert "Open character helper" in participate
    assert "@PublicText(card.Card.Summary)" in participate
    assert "@PublicText(milestone.CasualSummary)" in participate

    for forbidden in (
        "ALICE build ghosts",
        "Build Ghost concierge",
        "Open Build Ghost",
        "generated by AI",
        "AI-generated",
    ):
        assert forbidden not in participate


def test_signal_packet_source_uses_plain_public_copy_labels() -> None:
    packet = read("Chummer.Run.Api/Views/Shared/_PublicSignalProjectionPacket.cshtml")

    assert "Open the Chummer page" in packet
    assert "How this works" in packet
    assert "Limits" in packet
    assert "Public feedback can move into review" in packet
    assert "guided review path" in packet

    for forbidden in (
        "Open first-party fallback",
        "Boundary conditions",
        "sourceReceipts",
        "canonicalSources",
        "journeyProofEvents",
        "guided synthesis lane",
    ):
        assert forbidden not in packet


def test_public_humanizer_cleans_plural_internal_terms() -> None:
    humanizer = read("Chummer.Run.Api/Services/PublicFacingCopyHumanizer.cs")

    for phrase in (
        '("receipts", "records")',
        '("artifacts", "files")',
        '("proofs", "status details")',
        '("operators", "maintainers")',
        '("assistants", "help")',
    ):
        assert phrase in humanizer


def test_login_surface_uses_plain_account_and_claim_copy_language() -> None:
    entry = read("Chummer.Run.Api/Views/Auth/Entry.cshtml")

    assert "Claim your copy" in entry
    assert "Claim with email" in entry
    assert "Claim with your account" in entry

    for forbidden in (
        "Campaign OS",
        "roadmap follows",
        "preview interest",
        "optional participation state",
        "claim tickets",
    ):
        assert forbidden not in entry


def test_downloads_surface_hides_account_handoff_noise() -> None:
    downloads = read("Chummer.Run.Api/Views/PublicLanding/Downloads.cshtml")

    assert "Stable" in downloads
    assert "Nightly" in downloads
    assert "Windows" in downloads
    assert "Linux" in downloads
    assert "stableAndNightlyMatch" in downloads
    assert "Nightly currently matches Stable" in downloads
    assert "There is no newer Nightly available" in downloads

    for forbidden in (
        "Signed-in download",
        "recommended download",
        "manual activation",
        "install ticket",
        "short-lived install ticket",
        "Claim code",
        "claim code",
        "portable",
        "proof",
        "receipt",
        "Checked",
    ):
        assert forbidden not in downloads

    assert "Updated" in downloads


def test_minimal_palette_stays_neutral_and_readable() -> None:
    site_css = read("Chummer.Run.Api/wwwroot/css/site.css")

    assert "--minimal-page: #f7f8fa;" in site_css
    assert "--minimal-surface: #ffffff;" in site_css
    assert "rgba(255, 255, 255, 0.92)" in site_css
    assert "--minimal-page: #f7f6f2;" not in site_css
    assert "--minimal-surface: #fffefa;" not in site_css
    assert "--minimal-soft: #ece8df;" not in site_css
    assert ".surface-minimal .field input" in site_css
    assert ".surface-minimal .field select option" in site_css


def test_public_form_controls_have_os_dark_safe_defaults() -> None:
    site_css = read("Chummer.Run.Api/wwwroot/css/site.css")

    assert 'input:not([type="hidden"]):not([type="checkbox"]):not([type="radio"])' in site_css
    assert "select option,\nselect optgroup" in site_css
    assert "color-scheme: light;" in site_css
    assert "caret-color: var(--ink-strong);" in site_css
    assert "background: #ffffff;" in site_css
    assert "color: var(--ink-strong);" in site_css
    assert "::placeholder" in site_css
    assert "opacity: 1;" in site_css


def test_public_copy_uses_maintenance_language_instead_of_horizon_metaphor() -> None:
    sources = [
        read("Chummer.Run.Api/Views/PublicLanding/Horizons.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/FeatureDetail.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/_FeatureDetailRoadmap.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/Participate.cshtml"),
    ]
    combined = "\n".join(sources)

    for forbidden in (
        "Why this horizon matters now",
        "What following this horizon means",
        "This page names the horizon",
        "Move to Horizons",
        "current horizon",
        "named horizons",
        "Horizons already carrying public movement",
    ):
        assert forbidden not in combined

    assert "Maintenance" in combined
    assert "planned work" in combined


def test_campaign_city_pages_do_not_render_maintenance_console_words() -> None:
    sources = [
        read("Chummer.Run.Api/Views/PublicLanding/Ledger.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/LedgerAccountHome.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/LedgerAdvisory.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/LedgerOnboarding.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/LedgerFactionPromo.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/LedgerFactionWorkspace.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/LedgerNotifications.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/LedgerLeaderBriefing.cshtml"),
    ]
    combined = "\n".join(sources)

    for forbidden in (
        "Posture:",
        "Executive posture",
        "Current page posture",
        "Table posture",
        "Broadcast posture",
        "Quality checklist",
        "Your browser does not support HTML5 video playback for this route.",
        "platform posture",
        "Trust posture is not available",
        "aggregate install posture",
        "faction posture",
        "management posture",
        "Cross-district posture",
        "Verdict:",
        "Connected command lane",
        "Connected command path",
        "Faction workspace lanes",
        "Onboarding command lanes",
    ):
        assert forbidden not in combined

    assert "PublicFacingCopyHumanizer.Clean(Model.Promo.ProviderStatus)" in combined
    assert "PublicFacingCopyHumanizer.Clean(Model.PromoArtifact.ProviderStatus)" in combined
    assert "Your browser cannot play this video here." in combined


def test_signed_in_account_copy_uses_files_status_and_plain_download_language() -> None:
    account = read("Chummer.Run.Api/Views/Accounts/Account.cshtml")

    for forbidden in (
        "The artifact stays the same for everyone",
        "Artifact shelf posture",
        "Current release posture",
        "Known help and trust posture",
        "Quiet support posture",
        "Recovery posture",
        "Trust posture",
        "artifacts ·",
        "Restore posture",
        "Recent return artifact",
        "Move governed roster state",
        "Transfer governed roster state",
        "Staleness posture",
        "Conflict posture",
        "Recoverability posture",
        "Continue posture",
        "Governed prep",
        "governed prep",
        "Governed packet",
        "governed packet",
        "GM operations posture",
        "Search posture",
        "Binding posture",
        "Artifact publication",
        "governed operator view",
        "governed view",
        "Issue governed",
        "No governed",
        "Recent governed",
        "governed public discovery",
        "workspace lanes",
        "Grounded rule answer",
        "Package posture",
        "Recap and artifact shelf",
        "waiting for governed",
        "Record:",
        "Evidence:",
        "Lead:",
        "Authority:",
        "Surface:",
        "Route:",
        "Recovery path:",
        "Recovery link:",
        "Lead recovery hint:",
        "Latest record observed:",
        "Entitlement conflict records",
        "Safe-to-continue history",
        "Refresh-before-continue items",
        "Record consent to continue this access request.",
        "Not resumable from this record.",
        "Source summary",
        "Stale source history",
        "Legacy migration records",
        "record(s)",
        "File record",
        "carry-forward record",
        " Source: @output.ProvenanceSummary",
        " Source: @PublicText(item.ProvenanceSummary)",
        " Source: @HumanizeStatus(consequence.Receipts[0].SourceKind",
        " Source: @answer.ProvenanceLabel",
        " Source: @publication.ProvenanceSummary",
        "Target operator groups",
        "Source campaign",
        "Operator note",
        "Source-linked hints",
        "Source hint:",
        "Operator groups",
        "You are not currently the operator",
        "Operator watchouts",
        "No reviewed season or event records are attached yet.",
        "The internal continuity bridge recorded a participation event.",
    ):
        assert forbidden not in account

    assert "The download stays the same for everyone" in account
    assert "Access conflicts" in account
    assert "Ready history" in account
    assert "Needs refresh" in account
    assert "Account update" in account
    assert "Restore update" in account
    assert "Details:" in account
    assert "Recap files" in account
    assert "Restore status" in account
    assert "Move roster state" in account
    assert "Prep packet" in account
    assert "GM operations status" in account
    assert "Binding status" in account
    assert "Package status" in account
    assert "Current release status" in account
    assert "Help and privacy" in account
    assert "Recovery status" in account
    assert "PublicText(" in account
    assert "Save consent to continue this access request." in account
    assert "Not resumable from this action." in account
    assert "Stale history" in account
    assert "Legacy migration history" in account
    assert "File detail" in account
    assert "Details: @PublicText(output.ProvenanceSummary)" in account
    assert "Details: @PublicText(item.ProvenanceSummary)" in account
    assert "Details: @PublicText(answer.ProvenanceLabel)" in account
    assert "Details: @PublicText(publication.ProvenanceSummary)" in account
    assert "Target groups" in account
    assert "Original campaign" in account
    assert "Move note" in account
    assert "Travel note" in account
    assert "Prep note" in account
    assert "Package note" in account
    assert "Hint: @sourceHintLine" in account
    assert "You do not currently manage a campaign" in account
    assert "No reviewed season or event activity is attached yet." in account
    assert "A participation event was saved." in account


def test_specialist_public_surfaces_hide_raw_record_identifiers() -> None:
    sources = {
        "package_receipt": read("Chummer.Run.Api/Views/PublicLanding/PackageReceipt.cshtml"),
        "knowledge_fabric": read("Chummer.Run.Api/Views/PublicLanding/KnowledgeFabric.cshtml"),
        "nexus_pan": read("Chummer.Run.Api/Views/PublicLanding/NexusPanContinuity.cshtml"),
        "anarchy": read("Chummer.Run.Api/Views/PublicLanding/Anarchy.cshtml"),
        "ledger_account": read("Chummer.Run.Api/Views/PublicLanding/LedgerAccountHome.cshtml"),
        "ledger_faction_workspace": read("Chummer.Run.Api/Views/PublicLanding/LedgerFactionWorkspace.cshtml"),
        "ledger_notifications": read("Chummer.Run.Api/Views/PublicLanding/LedgerNotifications.cshtml"),
    }
    combined = "\n".join(sources.values())

    for forbidden in (
        "@PublicPackageText(Model.Receipt.ReceiptId)",
        "<span>@receipt.ReceiptId</span>",
        "<span>@receipt.Provenance</span>",
        "<span>@receipt.Route</span>",
        "<h3>@receipt.ReceiptId</h3>",
        "<h3>@Model.ExplainReceipt.ReceiptId</h3>",
        "Source: @dispatch.SourceReceiptId",
        "Source: @Model.ExplainReceipt.SourceReceiptId",
        "Delivery: @receipt.DeliveryRef",
        "View record",
        "Record summary",
        "without losing the record",
        "The record keeps",
        "Package records should not become a support workaround",
        "Stored records",
        "Decision sources",
    ):
        assert forbidden not in combined

    assert "Saved action" in sources["package_receipt"]
    assert "without losing the saved action" in sources["package_receipt"]
    assert "Package activity should not become a support workaround" in sources["package_receipt"]
    assert "Portable runner explanation" in sources["anarchy"]
    assert "Recent decision" in sources["ledger_account"]
    assert "Recent decision" in sources["ledger_faction_workspace"]
    assert "Delivery attempt" in sources["ledger_notifications"]
    assert "Saved updates" in sources["ledger_notifications"]
    assert "PublicFacingCopyHumanizer.Clean(receipt.Provenance)" in sources["knowledge_fabric"]
    assert "PublicFacingCopyHumanizer.Clean(receipt.Route)" in sources["nexus_pan"]


def test_feedback_operations_detail_hides_provider_and_record_ids_from_cards() -> None:
    feedback_operations = read("Chummer.Run.Api/Views/PublicLanding/FeedbackOperationsDetail.cshtml")
    signal_operations = read("Chummer.Run.Api/Views/Shared/_PublicSignalOperationsPacket.cshtml")

    for forbidden in (
        "<span>@sourceReceipt.ReceiptId</span>",
        "<span>@sourceReceipt.ProviderEventId</span>",
        "<span>@receipt.ReceiptId</span>",
        "<span>@receipt.DeliveryId</span>",
        "<span>@receipt.RecipientRef</span>",
        "<span>@receipt.AddressHash</span>",
        "<span>@receipt.TemplateVersion</span>",
        "<span>@receipt.ConsentSourceRef</span>",
        "<span>@receipt.SuppressionCheck</span>",
        "<span>@receipt.GovernorDecisionRef</span>",
        "<span>@receipt.ProviderMessageId</span>",
        "<span>@receipt.DispatchReceiptId</span>",
        "<span>@thread.AddressHash</span>",
        "<span>@thread.DispatchReceiptId</span>",
        "<h3>@thread.RecipientRef</h3>",
        "<h3>@receipt.TemplateId",
        "<h3>@receipt.EventKey</h3>",
        "message record",
        "follow-up record",
        "routing record",
        "source record",
        "release record",
        "<p class=\"eyebrow\">Source item</p>",
        "The originating source item",
        "Open source details",
        "ReleaseProofReceiptId",
        "ReleaseProofRoute",
    ):
        assert forbidden not in feedback_operations

    for forbidden in (
        "follow-up record",
        "posted follow-up record",
    ):
        assert forbidden not in signal_operations

    assert "Original item" in feedback_operations
    assert "Open related details" in feedback_operations
    assert "Download related data" in feedback_operations
    assert "posted follow-up update" in signal_operations
    assert "message update" in feedback_operations
    assert "follow-up update" in feedback_operations
    assert "routing update" in feedback_operations
    assert "Recipient thread" in feedback_operations
    assert "Message updates" in feedback_operations
    assert "Message attempt" in feedback_operations
    assert "Follow-up sent" in feedback_operations


def test_public_submission_and_home_pages_hide_raw_ids_and_source_labels() -> None:
    support_submitted = read("Chummer.Run.Api/Views/PublicLanding/SupportSubmitted.cshtml")
    karma_submitted = read("Chummer.Run.Api/Views/PublicLanding/KarmaForgeSubmitted.cshtml")
    home = read("Chummer.Run.Api/Views/PublicLanding/Home.cshtml")
    combined = "\n".join((support_submitted, karma_submitted, home))

    for forbidden in (
        "<span>@Model.CaseId</span>",
        "Keep the case id nearby",
        "one stable id",
        "same case id",
        "<span>@Model.SubmissionId</span>",
        "<span>@stage.ReceiptId</span>",
        "Source: @leadAftermathShelfEntry.ProvenanceSummary",
        "Output source: @output.ProvenanceSummary",
        "Source: @answer.ProvenanceLabel",
        "Source: @publication.ProvenanceSummary",
        "Source-linked hints",
        "Source hint:",
    ):
        assert forbidden not in combined

    assert "Report saved" in support_submitted
    assert "Submission saved" in karma_submitted
    assert "Step saved" in karma_submitted
    assert "Details: @PublicFacingCopyHumanizer.Clean(leadAftermathShelfEntry.ProvenanceSummary)" in home
    assert "Output details: @PublicFacingCopyHumanizer.Clean(output.ProvenanceSummary)" in home
    assert "Details: @PublicFacingCopyHumanizer.Clean(answer.ProvenanceLabel)" in home
    assert "Details: @PublicFacingCopyHumanizer.Clean(publication.ProvenanceSummary)" in home
    assert "Hint: @sourceHintLine" in home


def test_public_lookup_and_leaderboards_use_plain_history_language() -> None:
    lookup = read("Chummer.Run.Api/Views/PublicLanding/FeedbackOperationsLookup.cshtml")
    leaderboards = read("Chummer.Run.Api/Views/Leaderboards/Index.cshtml")
    combined = "\n".join((lookup, leaderboards))

    for forbidden in (
        "Search by source id",
        "Sources and threads",
        "Source records only",
        "Chummer records",
        "stored state",
        "source records",
        "No record or thread matched this query",
        "Open lookup artifact",
        "Open detail artifact",
        "<th scope=\"col\">Records</th>",
    ):
        assert forbidden not in combined

    assert "Search by item id" in lookup
    assert "Items and threads" in lookup
    assert "Items only" in lookup
    assert "Chummer history" in lookup
    assert "saved state" in lookup
    assert "saved items" in lookup
    assert "No item or thread matched this query" in lookup
    assert "Open lookup data" in lookup
    assert "Open detail data" in lookup
    assert "<th scope=\"col\">Entries</th>" in leaderboards


def test_specialized_public_pages_avoid_operator_artifact_record_copy() -> None:
    codex = read("Chummer.Run.Api/Views/CodexParticipation/Console.cshtml")
    release_upload = read("Chummer.Run.Api/Views/PublicLanding/ReleaseUpload.cshtml")
    gm_session = read("Chummer.Run.Api/Views/PublicLanding/GmSessionVenue.cshtml")
    ledger = read("Chummer.Run.Api/Views/PublicLanding/Ledger.cshtml")
    roadmap_detail = read("Chummer.Run.Api/Views/PublicLanding/_FeatureDetailRoadmap.cshtml")
    combined = "\n".join((codex, release_upload, gm_session, ledger, roadmap_detail))

    for forbidden in (
        "participation record",
        "keeps the record",
        "desktop artifact",
        "packaging artifacts",
        "validates the bundle",
        "platform artifact",
        "promoted artifact",
        "campaign record",
        "Source details",
        "publication record",
    ):
        assert forbidden not in combined

    assert "participation history" in codex
    assert "keeps the history" in codex
    assert "desktop app" in release_upload
    assert "packaging files" in release_upload
    assert "accepts the bundle" in release_upload
    assert "platform file" in release_upload
    assert "promoted file" in release_upload
    assert "campaign history" in gm_session
    assert "Details</a>" in ledger
    assert "publication history" in roadmap_detail


def test_package_and_publication_pages_use_activity_and_details_language() -> None:
    packages = read("Chummer.Run.Api/Views/PublicLanding/Packages.cshtml")
    package_detail = read("Chummer.Run.Api/Views/PublicLanding/PackageDetail.cshtml")
    shelf = read("Chummer.Run.Api/Views/PublicLanding/Shelf.cshtml")
    publication = read("Chummer.Run.Api/Views/PublicLanding/PublicCreatorPublication.cshtml")
    combined = "\n".join((packages, package_detail, shelf, publication))

    for forbidden in (
        "Your recent package records",
        "Recent records",
        "No records yet",
        "Open record",
        "Source:",
        "<span class=\"tag\">Source</span>",
        "source context",
        "shared record",
        "creator-publication record",
        "required item",
    ):
        assert forbidden not in combined

    assert "Your recent package activity" in packages
    assert "Recent activity" in package_detail
    assert "Open activity" in package_detail
    assert "Details:</strong> @PublicFacingCopyHumanizer.Clean(publication.ProvenanceSummary)" in shelf
    assert "<span class=\"tag\">Details</span>" in publication
    assert "supporting detail" in publication
