from __future__ import annotations

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]


def read(relative_path: str) -> str:
    return (REPO_ROOT / relative_path).read_text(encoding="utf-8")


def test_main_public_routes_use_minimal_surface_contract() -> None:
    landing = read("Chummer.Run.Api/Views/PublicLanding/Landing.cshtml")
    downloads = read("Chummer.Run.Api/Views/PublicLanding/Downloads.cshtml")
    status = read("Chummer.Run.Api/Views/PublicLanding/Status.cshtml")
    horizons = read("Chummer.Run.Api/Views/PublicLanding/Horizons.cshtml")
    product_story = read("Chummer.Run.Api/Views/PublicLanding/ProductStory.cshtml")
    faq = read("Chummer.Run.Api/Views/PublicLanding/Faq.cshtml")
    trust_page = read("Chummer.Run.Api/Views/PublicLanding/TrustPage.cshtml")

    for source in (landing, downloads, status, horizons, product_story, faq):
        assert 'surface-minimal' in source

    assert 'surface-help surface-minimal' in trust_page
    assert 'minimal-help-grid' in trust_page
    assert 'minimal-help-card' in trust_page
    assert 'Pick one path' in trust_page
    assert 'other options below' in trust_page
    assert 'other routes below' not in trust_page


def test_public_front_door_hides_unready_campaign_and_ai_language() -> None:
    landing = read("Chummer.Run.Api/Views/PublicLanding/Landing.cshtml")
    horizons = read("Chummer.Run.Api/Views/PublicLanding/Horizons.cshtml")
    product_story = read("Chummer.Run.Api/Views/PublicLanding/ProductStory.cshtml")

    for source in (landing, horizons, product_story):
        assert "Black Ledger" not in source
        assert "generated by AI" not in source
        assert "AI-generated" not in source
        assert "proof receipt" not in source
        assert "artifact-gallery" not in source

    assert "Not the front door" in horizons
    assert "Downloads first" in horizons


def test_homepage_has_minimal_product_video_surface() -> None:
    landing = read("Chummer.Run.Api/Views/PublicLanding/Landing.cshtml")
    site_css = read("Chummer.Run.Api/wwwroot/css/site.css")

    assert 'class="minimal-video"' in landing
    assert 'aria-label="Product video"' in landing
    assert "/media/promo/chummer6-flagship-promo.mp4" in landing
    assert "/media/promo/chummer6-flagship-promo.webm" in landing
    assert "/media/promo/chummer6-flagship-promo.vtt" in landing
    assert ".minimal-video" in site_css
    assert "aspect-ratio: 16 / 9;" in site_css

    for forbidden in (
        "proof",
        "receipt",
        "artifact",
        "generated by AI",
        "AI-generated",
    ):
        assert forbidden not in landing


def test_public_views_use_neutral_note_markup_instead_of_proof_markup() -> None:
    public_views = [
        "Chummer.Run.Api/Views/PublicLanding/Changelog.cshtml",
        "Chummer.Run.Api/Views/PublicLanding/Feedback.cshtml",
        "Chummer.Run.Api/Views/PublicLanding/Participate.cshtml",
    ]

    for view_path in public_views:
        source = read(view_path)
        assert "workflow-card__proof" not in source
        assert "workflow-card__note" in source


def test_participation_surface_uses_plain_character_helper_copy() -> None:
    participate = read("Chummer.Run.Api/Views/PublicLanding/Participate.cshtml")

    assert "Character help preview" in participate
    assert "Open character helper" in participate
    assert "@PublicText(card.Card.Summary)" in participate
    assert "@PublicText(milestone.CasualSummary)" in participate

    for forbidden in (
        "ALICE build ghosts",
        "Build Ghost concierge",
        "Open Build Ghost",
        "generated by AI",
        "AI-generated",
    ):
        assert forbidden not in participate


def test_signal_packet_source_uses_plain_public_copy_labels() -> None:
    packet = read("Chummer.Run.Api/Views/Shared/_PublicSignalProjectionPacket.cshtml")

    assert "Open the Chummer page" in packet
    assert "How this works" in packet
    assert "Limits" in packet
    assert "Public feedback can move into review" in packet
    assert "guided review path" in packet

    for forbidden in (
        "Open first-party fallback",
        "Boundary conditions",
        "sourceReceipts",
        "canonicalSources",
        "journeyProofEvents",
        "guided synthesis lane",
        "guided review lane",
    ):
        assert forbidden not in packet


def test_karma_forge_surfaces_use_plain_review_language() -> None:
    karma_forge = read("Chummer.Run.Api/Views/PublicLanding/KarmaForge.cshtml")
    karma_submitted = read("Chummer.Run.Api/Views/PublicLanding/KarmaForgeSubmitted.cshtml")
    combined = "\n".join((karma_forge, karma_submitted))

    assert "guided review path" in combined
    assert "review path" in combined
    assert "id=\"review-next-steps\"" in karma_submitted

    for forbidden in (
        "guided synthesis lane",
        "guided review lane",
        "bounded-followthrough",
        "new PublicNavigationLink(\"Next steps\", \"#bounded-followthrough\")",
    ):
        assert forbidden not in combined


def test_connected_table_pulse_sources_do_not_keep_legacy_marker_comments() -> None:
    sources = [
        read("Chummer.Run.Api/Views/Accounts/Account.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/Landing.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/Home.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/Shelf.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/MediaArtifactHorizon.cshtml"),
    ]
    combined = "\n".join(sources)

    for forbidden in (
        "legacy source marker",
        "command-to-fallout lane",
        "Aftermath return lane",
        "Open aftermath rail",
        "governed workspace",
        "Connected lane",
        "Release proof",
        "Open starter lane on Home",
        "Starter lane",
        "Campaign-ready lane",
    ):
        assert forbidden not in combined


def test_public_humanizer_cleans_plural_internal_terms() -> None:
    humanizer = read("Chummer.Run.Api/Services/PublicFacingCopyHumanizer.cs")

    for phrase in (
        '("receipts", "records")',
        '("artifacts", "files")',
        '("proofs", "status details")',
        '("operators", "maintainers")',
        '("assistants", "help")',
    ):
        assert phrase in humanizer


def test_login_surface_uses_plain_account_and_claim_copy_language() -> None:
    entry = read("Chummer.Run.Api/Views/Auth/Entry.cshtml")

    assert "Claim your copy" in entry
    assert "Claim with email" in entry
    assert "Claim with your account" in entry

    for forbidden in (
        "Campaign OS",
        "roadmap follows",
        "preview interest",
        "optional participation state",
        "claim tickets",
    ):
        assert forbidden not in entry


def test_downloads_surface_hides_account_handoff_noise() -> None:
    downloads = read("Chummer.Run.Api/Views/PublicLanding/Downloads.cshtml")

    assert "Stable" in downloads
    assert "Nightly" in downloads
    assert "Windows" in downloads
    assert "Linux" in downloads
    assert "stableAndNightlyMatch" in downloads
    assert "Nightly currently matches Stable" in downloads
    assert "There is no newer Nightly available" in downloads

    for forbidden in (
        "Signed-in download",
        "recommended download",
        "manual activation",
        "install ticket",
        "short-lived install ticket",
        "Claim code",
        "claim code",
        "portable",
        "proof",
        "receipt",
        "Checked",
    ):
        assert forbidden not in downloads

    assert "Updated" in downloads


def test_minimal_palette_stays_neutral_and_readable() -> None:
    site_css = read("Chummer.Run.Api/wwwroot/css/site.css")

    assert "--minimal-page: #f7f8fa;" in site_css
    assert "--minimal-surface: #ffffff;" in site_css
    assert "rgba(255, 255, 255, 0.92)" in site_css
    assert "--minimal-page: #f7f6f2;" not in site_css
    assert "--minimal-surface: #fffefa;" not in site_css
    assert "--minimal-soft: #ece8df;" not in site_css
    assert ".surface-minimal .field input" in site_css
    assert ".surface-minimal .field select option" in site_css


def test_public_form_controls_have_os_dark_safe_defaults() -> None:
    site_css = read("Chummer.Run.Api/wwwroot/css/site.css")

    assert 'input:not([type="hidden"]):not([type="checkbox"]):not([type="radio"])' in site_css
    assert "select option,\nselect optgroup" in site_css
    assert "color-scheme: light;" in site_css
    assert "caret-color: var(--ink-strong);" in site_css
    assert "background: #ffffff;" in site_css
    assert "color: var(--ink-strong);" in site_css
    assert "::placeholder" in site_css
    assert "opacity: 1;" in site_css


def test_public_copy_uses_maintenance_language_instead_of_horizon_metaphor() -> None:
    sources = [
        read("Chummer.Run.Api/Views/PublicLanding/Horizons.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/FeatureDetail.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/_FeatureDetailRoadmap.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/Participate.cshtml"),
    ]
    combined = "\n".join(sources)

    for forbidden in (
        "Why this horizon matters now",
        "What following this horizon means",
        "This page names the horizon",
        "Move to Horizons",
        "current horizon",
        "named horizons",
        "Horizons already carrying public movement",
    ):
        assert forbidden not in combined

    assert "Maintenance" in combined
    assert "planned work" in combined


def test_roadmap_pages_clean_dynamic_copy_before_rendering() -> None:
    roadmap = read("Chummer.Run.Api/Views/PublicLanding/Roadmap.cshtml")
    roadmap_detail = read("Chummer.Run.Api/Views/PublicLanding/_FeatureDetailRoadmap.cshtml")

    for required in (
        "@CalmRoadmapText(milestone.StatusLabel)",
        "@CalmRoadmapText(dependency.StatusLabel)",
        "@CalmRoadmapText(signalLoop.FollowSettingsLabel)",
    ):
        assert required in roadmap

    for required in (
        "static string RoadmapText(string? value)",
        "@RoadmapText(Model.Pain)",
        "@RoadmapText(Model.Payoff)",
        "@RoadmapText(Model.PrimaryAction.Label)",
    ):
        assert required in roadmap_detail

    for forbidden in (
        "@milestone.StatusLabel",
        "@dependency.StatusLabel",
        "@signalLoop.FollowSettingsLabel",
    ):
        assert forbidden not in roadmap

    for forbidden in (
        "@Model.Pain",
        "@Model.Payoff",
        "@Model.PrimaryAction.Label",
    ):
        assert forbidden not in roadmap_detail


def test_campaign_city_pages_do_not_render_maintenance_console_words() -> None:
    sources = [
        read("Chummer.Run.Api/Views/PublicLanding/Ledger.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/LedgerAccountHome.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/LedgerAdvisory.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/LedgerOnboarding.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/LedgerFactionPromo.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/LedgerFactionWorkspace.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/LedgerNotifications.cshtml"),
        read("Chummer.Run.Api/Views/PublicLanding/LedgerLeaderBriefing.cshtml"),
    ]
    combined = "\n".join(sources)

    for forbidden in (
        "Posture:",
        "Executive posture",
        "Current page posture",
        "Table posture",
        "Broadcast posture",
        "Quality checklist",
        "Your browser does not support HTML5 video playback for this route.",
        "platform posture",
        "Trust posture is not available",
        "aggregate install posture",
        "faction posture",
        "management posture",
        "Cross-district posture",
        "Verdict:",
        "Connected command lane",
        "Connected command path",
        "Faction workspace lanes",
        "Onboarding command lanes",
        "Fallback mode:",
        "faction-storyboard-frame__proof",
    ):
        assert forbidden not in combined

    assert "PublicFacingCopyHumanizer.Clean(Model.Promo.ProviderStatus)" in combined
    assert "PublicFacingCopyHumanizer.Clean(Model.PromoArtifact.ProviderStatus)" in combined
    assert "Your browser cannot play this video here." in combined


def test_signed_in_account_copy_uses_files_status_and_plain_download_language() -> None:
    account = read("Chummer.Run.Api/Views/Accounts/Account.cshtml")

    for forbidden in (
        "The artifact stays the same for everyone",
        "Artifact shelf posture",
        "Current release posture",
        "Known help and trust posture",
        "Quiet support posture",
        "Recovery posture",
        "Trust posture",
        "artifacts ·",
        "Restore posture",
        "Recent return artifact",
        "Move governed roster state",
        "Transfer governed roster state",
        "Staleness posture",
        "Conflict posture",
        "Recoverability posture",
        "Continue posture",
        "Governed prep",
        "governed prep",
        "Governed packet",
        "governed packet",
        "GM operations posture",
        "Search posture",
        "Binding posture",
        "Artifact publication",
        "governed operator view",
        "governed view",
        "Issue governed",
        "No governed",
        "Recent governed",
        "governed public discovery",
        "workspace lanes",
        "Grounded rule answer",
        "Package posture",
        "Recap and artifact shelf",
        "waiting for governed",
        "Record:",
        "Evidence:",
        "Lead:",
        "Authority:",
        "Surface:",
        "Route:",
        "Recovery path:",
        "Recovery link:",
        "Lead recovery hint:",
        "Latest record observed:",
        "Entitlement conflict records",
        "Safe-to-continue history",
        "Refresh-before-continue items",
        "Record consent to continue this access request.",
        "Not resumable from this record.",
        "Source summary",
        "Stale source history",
        "Legacy migration records",
        "record(s)",
        "File record",
        "carry-forward record",
        " Source: @output.ProvenanceSummary",
        " Source: @PublicText(item.ProvenanceSummary)",
        " Source: @HumanizeStatus(consequence.Receipts[0].SourceKind",
        " Source: @answer.ProvenanceLabel",
        " Source: @publication.ProvenanceSummary",
        "Target operator groups",
        "Source campaign",
        "Operator note",
        "Source-linked hints",
        "Source hint:",
        "Operator groups",
        "You are not currently the operator",
        "Operator watchouts",
        "No reviewed season or event records are attached yet.",
        "The internal continuity bridge recorded a participation event.",
    ):
        assert forbidden not in account

    assert "The download stays the same for everyone" in account
    assert "Access conflicts" in account
    assert "Ready history" in account
    assert "Needs refresh" in account
    assert "Account update" in account
    assert "Restore update" in account
    assert "Details:" in account
    assert "Recap files" in account
    assert "Restore status" in account
    assert "Move roster state" in account
    assert "Prep packet" in account
    assert "GM operations status" in account
    assert "Binding status" in account
    assert "Package status" in account
    assert "Current release status" in account
    assert "Help and privacy" in account
    assert "Recovery status" in account
    assert "PublicText(" in account
    assert "Save consent to continue this access request." in account
    assert "Not resumable from this action." in account
    assert "Stale history" in account
    assert "Legacy migration history" in account
    assert "File detail" in account
    assert "Details: @PublicText(output.ProvenanceSummary)" in account
    assert "Details: @PublicText(item.ProvenanceSummary)" in account
    assert "Details: @PublicText(answer.ProvenanceLabel)" in account
    assert "Details: @PublicText(publication.ProvenanceSummary)" in account
    assert "Target groups" in account
    assert "Original campaign" in account
    assert "Move note" in account
    assert "Travel note" in account
    assert "Prep note" in account
    assert "Package note" in account
    assert "Hint: @sourceHintLine" in account
    assert "You do not currently manage a campaign" in account
    assert "No reviewed season or event activity is attached yet." in account
    assert "A participation event was saved." in account


def test_specialist_public_surfaces_hide_raw_record_identifiers() -> None:
    sources = {
        "package_receipt": read("Chummer.Run.Api/Views/PublicLanding/PackageReceipt.cshtml"),
        "knowledge_fabric": read("Chummer.Run.Api/Views/PublicLanding/KnowledgeFabric.cshtml"),
        "nexus_pan": read("Chummer.Run.Api/Views/PublicLanding/NexusPanContinuity.cshtml"),
        "anarchy": read("Chummer.Run.Api/Views/PublicLanding/Anarchy.cshtml"),
        "ledger_account": read("Chummer.Run.Api/Views/PublicLanding/LedgerAccountHome.cshtml"),
        "ledger_faction_workspace": read("Chummer.Run.Api/Views/PublicLanding/LedgerFactionWorkspace.cshtml"),
        "ledger_notifications": read("Chummer.Run.Api/Views/PublicLanding/LedgerNotifications.cshtml"),
    }
    combined = "\n".join(sources.values())

    for forbidden in (
        "@PublicPackageText(Model.Receipt.ReceiptId)",
        "<span>@receipt.ReceiptId</span>",
        "<span>@receipt.Provenance</span>",
        "<span>@receipt.Route</span>",
        "<h3>@receipt.ReceiptId</h3>",
        "<h3>@Model.ExplainReceipt.ReceiptId</h3>",
        "Source: @dispatch.SourceReceiptId",
        "Source: @Model.ExplainReceipt.SourceReceiptId",
        "Delivery: @receipt.DeliveryRef",
        "View record",
        "Record summary",
        "without losing the record",
        "The record keeps",
        "Package records should not become a support workaround",
        "Stored records",
        "Decision sources",
    ):
        assert forbidden not in combined

    assert "Saved action" in sources["package_receipt"]
    assert "without losing the saved action" in sources["package_receipt"]
    assert "Package activity should not become a support workaround" in sources["package_receipt"]
    assert "Portable runner explanation" in sources["anarchy"]
    assert "Recent decision" in sources["ledger_account"]
    assert "Recent decision" in sources["ledger_faction_workspace"]
    assert "Delivery attempt" in sources["ledger_notifications"]
    assert "Saved updates" in sources["ledger_notifications"]
    assert "PublicFacingCopyHumanizer.Clean(receipt.Provenance)" in sources["knowledge_fabric"]
    assert "PublicFacingCopyHumanizer.Clean(receipt.Route)" in sources["nexus_pan"]


def test_feedback_operations_detail_hides_provider_and_record_ids_from_cards() -> None:
    feedback_operations = read("Chummer.Run.Api/Views/PublicLanding/FeedbackOperationsDetail.cshtml")
    signal_operations = read("Chummer.Run.Api/Views/Shared/_PublicSignalOperationsPacket.cshtml")

    for forbidden in (
        "<span>@sourceReceipt.ReceiptId</span>",
        "<span>@sourceReceipt.ProviderEventId</span>",
        "<span>@receipt.ReceiptId</span>",
        "<span>@receipt.DeliveryId</span>",
        "<span>@receipt.RecipientRef</span>",
        "<span>@receipt.AddressHash</span>",
        "<span>@receipt.TemplateVersion</span>",
        "<span>@receipt.ConsentSourceRef</span>",
        "<span>@receipt.SuppressionCheck</span>",
        "<span>@receipt.GovernorDecisionRef</span>",
        "<span>@receipt.ProviderMessageId</span>",
        "<span>@receipt.DispatchReceiptId</span>",
        "<span>@thread.AddressHash</span>",
        "<span>@thread.DispatchReceiptId</span>",
        "<h3>@thread.RecipientRef</h3>",
        "<h3>@receipt.TemplateId",
        "<h3>@receipt.EventKey</h3>",
        "message record",
        "follow-up record",
        "routing record",
        "source record",
        "release record",
        "<p class=\"eyebrow\">Source item</p>",
        "The originating source item",
        "Open source details",
        "ReleaseProofReceiptId",
        "ReleaseProofRoute",
        "Download related data",
        "Download thread data",
        "Download item data",
    ):
        assert forbidden not in feedback_operations

    for forbidden in (
        "follow-up record",
        "posted follow-up record",
        "private-support crossover",
        "private-support item",
        "Category routing",
        "Public feedback stays easy to route.",
        "Public signal routing stays transparent",
    ):
        assert forbidden not in signal_operations

    assert "Original item" in feedback_operations
    assert "Open related details" in feedback_operations
    assert "Download related details" in feedback_operations
    assert "Download message details" in feedback_operations
    assert "Download item details" in feedback_operations
    assert "posted follow-up update" in signal_operations
    assert "message update" in feedback_operations
    assert "follow-up update" in feedback_operations
    assert "routing update" in feedback_operations
    assert "Recipient thread" in feedback_operations
    assert "Message updates" in feedback_operations
    assert "Message attempt" in feedback_operations
    assert "Follow-up sent" in feedback_operations
    assert "likely private support follow-up" in signal_operations
    assert "Feedback sorting" in signal_operations
    assert "Public feedback stays easy to sort." in signal_operations
    assert "Public feedback stays visible; private follow-up goes through Help." in signal_operations


def test_public_submission_and_home_pages_hide_raw_ids_and_source_labels() -> None:
    support_submitted = read("Chummer.Run.Api/Views/PublicLanding/SupportSubmitted.cshtml")
    karma_submitted = read("Chummer.Run.Api/Views/PublicLanding/KarmaForgeSubmitted.cshtml")
    home = read("Chummer.Run.Api/Views/PublicLanding/Home.cshtml")
    combined = "\n".join((support_submitted, karma_submitted, home))

    for forbidden in (
        "<span>@Model.CaseId</span>",
        "Keep the case id nearby",
        "one stable id",
        "same case id",
        "<span>@Model.SubmissionId</span>",
        "<span>@stage.ReceiptId</span>",
        "Source: @leadAftermathShelfEntry.ProvenanceSummary",
        "Output source: @output.ProvenanceSummary",
        "Source: @answer.ProvenanceLabel",
        "Source: @publication.ProvenanceSummary",
        "Source-linked hints",
        "Source hint:",
    ):
        assert forbidden not in combined

    assert "Report saved" in support_submitted
    assert "Submission saved" in karma_submitted
    assert "Step saved" in karma_submitted
    assert "Details: @PublicFacingCopyHumanizer.Clean(leadAftermathShelfEntry.ProvenanceSummary)" in home
    assert "Output details: @PublicFacingCopyHumanizer.Clean(output.ProvenanceSummary)" in home
    assert "Details: @PublicFacingCopyHumanizer.Clean(answer.ProvenanceLabel)" in home
    assert "Details: @PublicFacingCopyHumanizer.Clean(publication.ProvenanceSummary)" in home
    assert "Hint: @PublicText(sourceHintLine)" in home


def test_public_lookup_and_leaderboards_use_plain_history_language() -> None:
    lookup = read("Chummer.Run.Api/Views/PublicLanding/FeedbackOperationsLookup.cshtml")
    leaderboards = read("Chummer.Run.Api/Views/Leaderboards/Index.cshtml")
    combined = "\n".join((lookup, leaderboards))

    for forbidden in (
        "Search by source id",
        "Sources and threads",
        "Source records only",
        "Chummer records",
        "stored state",
        "source records",
        "No record or thread matched this query",
        "Open lookup artifact",
        "Open detail artifact",
        "<th scope=\"col\">Records</th>",
    ):
        assert forbidden not in combined

    assert "Search by item id" in lookup
    assert "Items and threads" in lookup
    assert "Items only" in lookup
    assert "Chummer history" in lookup
    assert "saved state" in lookup
    assert "saved items" in lookup
    assert "No item or thread matched this query" in lookup
    assert "Open lookup data" in lookup
    assert "Open detail data" in lookup
    assert "<th scope=\"col\">Entries</th>" in leaderboards


def test_specialized_public_pages_avoid_operator_artifact_record_copy() -> None:
    codex = read("Chummer.Run.Api/Views/CodexParticipation/Console.cshtml")
    release_upload = read("Chummer.Run.Api/Views/PublicLanding/ReleaseUpload.cshtml")
    gm_session = read("Chummer.Run.Api/Views/PublicLanding/GmSessionVenue.cshtml")
    ledger = read("Chummer.Run.Api/Views/PublicLanding/Ledger.cshtml")
    roadmap_detail = read("Chummer.Run.Api/Views/PublicLanding/_FeatureDetailRoadmap.cshtml")
    combined = "\n".join((codex, release_upload, gm_session, ledger, roadmap_detail))

    for forbidden in (
        "participation record",
        "keeps the record",
        "desktop artifact",
        "packaging artifacts",
        "validates the bundle",
        "platform artifact",
        "promoted artifact",
        "campaign record",
        "Source details",
        "publication record",
    ):
        assert forbidden not in combined

    assert "participation history" in codex
    assert "keeps the history" in codex
    assert "desktop app" in release_upload
    assert "packaging files" in release_upload
    assert "accepts the bundle" in release_upload
    assert "platform file" in release_upload
    assert "promoted file" in release_upload
    assert "campaign history" in gm_session
    assert "Details</a>" in ledger
    assert "publication history" in roadmap_detail


def test_package_and_publication_pages_use_activity_and_details_language() -> None:
    packages = read("Chummer.Run.Api/Views/PublicLanding/Packages.cshtml")
    package_detail = read("Chummer.Run.Api/Views/PublicLanding/PackageDetail.cshtml")
    shelf = read("Chummer.Run.Api/Views/PublicLanding/Shelf.cshtml")
    publication = read("Chummer.Run.Api/Views/PublicLanding/PublicCreatorPublication.cshtml")
    combined = "\n".join((packages, package_detail, shelf, publication))

    for forbidden in (
        "Your recent package records",
        "Recent records",
        "No records yet",
        "Open record",
        "Source:",
        "<span class=\"tag\">Source</span>",
        "source context",
        "shared record",
        "creator-publication record",
        "required item",
    ):
        assert forbidden not in combined

    assert "Your recent package activity" in packages
    assert "Recent activity" in package_detail
    assert "Open activity" in package_detail
    assert "@PublicPackageText(receipt.ActorLabel)" in packages
    assert "@PublicPackageText(Model.PrimaryAction.Label)" in package_detail
    assert "@PublicPackageText(Model.SecondaryAction.Label)" in package_detail
    assert "@PublicPackageText(Model.VoteActionLabel)" in package_detail
    assert "@PublicPackageText(Model.FollowActionLabel)" in package_detail
    assert "@PublicPackageText(receipt.ActorLabel)" in package_detail
    assert "@receipt.ActorLabel" not in packages
    assert "@receipt.ActorLabel" not in package_detail
    assert "@Model.PrimaryAction.Label" not in package_detail
    assert "@Model.SecondaryAction.Label" not in package_detail
    assert "@Model.VoteActionLabel" not in package_detail
    assert "@Model.FollowActionLabel" not in package_detail
    assert "Details:</strong> @PublicFacingCopyHumanizer.Clean(publication.ProvenanceSummary)" in shelf
    assert "<span class=\"tag\">Details</span>" in publication
    assert "related detail" in publication


def test_public_pages_use_plain_chummer_labels_instead_of_first_party_jargon() -> None:
    shelf = read("Chummer.Run.Api/Views/PublicLanding/Shelf.cshtml")
    changelog = read("Chummer.Run.Api/Views/PublicLanding/Changelog.cshtml")
    support_submitted = read("Chummer.Run.Api/Views/PublicLanding/SupportSubmitted.cshtml")
    publication = read("Chummer.Run.Api/Views/PublicLanding/PublicCreatorPublication.cshtml")
    nexus_pan = read("Chummer.Run.Api/Views/PublicLanding/NexusPanContinuity.cshtml")
    ledger_notifications = read("Chummer.Run.Api/Views/PublicLanding/LedgerNotifications.cshtml")
    ledger = read("Chummer.Run.Api/Views/PublicLanding/Ledger.cshtml")
    ledger_onboarding = read("Chummer.Run.Api/Views/PublicLanding/LedgerOnboarding.cshtml")
    combined = "\n".join((
        shelf,
        changelog,
        support_submitted,
        publication,
        nexus_pan,
        ledger_notifications,
        ledger,
        ledger_onboarding,
    ))

    for forbidden in (
        "first-party help",
        "First-party help",
        "first-party page",
        "first-party route",
        "first-party storage",
        "first-party email",
        "first-party motion",
        "product claims",
    ):
        assert forbidden not in combined

    assert "Chummer help" in shelf
    assert "Chummer help" in changelog
    assert "Chummer help" in support_submitted
    assert "Use Chummer help" in publication
    assert "tracked by Chummer" in nexus_pan
    assert "one Chummer path" in ledger_notifications
    assert "Delivery: Chummer email" in ledger
    assert "Chummer motion intros" in ledger
    assert "Video: Chummer motion" in ledger
    assert "Video: Chummer motion" in ledger_onboarding
    assert "product improvements" in changelog


def test_public_pages_use_plain_promises_and_summaries_instead_of_claim_jargon() -> None:
    anarchy = read("Chummer.Run.Api/Views/PublicLanding/Anarchy.cshtml")
    participate = read("Chummer.Run.Api/Views/PublicLanding/Participate.cshtml")
    feedback_lookup = read("Chummer.Run.Api/Views/PublicLanding/FeedbackOperationsLookup.cshtml")
    combined = "\n".join((anarchy, participate, feedback_lookup))

    for forbidden in (
        "Public claim ceiling",
        "public claim",
        "planned or shipped public claim",
    ):
        assert forbidden not in combined

    assert "What this path covers" in anarchy
    assert "planned or shipped public update" in participate
    assert "no public summary beyond the saved state" in feedback_lookup


def test_public_release_copy_uses_install_notes_instead_of_issue_checking_language() -> None:
    shelf = read("Chummer.Run.Api/Views/PublicLanding/Shelf.cshtml")
    now = read("Chummer.Run.Api/Views/PublicLanding/Now.cshtml")
    faq = read("Chummer.Run.Api/Views/PublicLanding/Faq.cshtml")
    feature_live = read("Chummer.Run.Api/Views/PublicLanding/_FeatureDetailLiveProof.cshtml")
    combined = "\n".join((shelf, now, faq, feature_live))

    for forbidden in (
        "check known issues",
        "Downloads shows the current package, known issues, and setup help",
        "Read download help and known issues",
        "Known issues and install help",
        "easier to trust",
    ):
        assert forbidden not in combined

    assert "see install notes" in shelf
    assert "current package, setup help" in now
    assert "Install notes and help" in now
    assert "current package and setup help" in faq
    assert "easier to use" in feature_live


def test_now_page_cleans_dynamic_public_copy_before_rendering() -> None:
    now = read("Chummer.Run.Api/Views/PublicLanding/Now.cshtml")

    for expected in (
        "static string PublicNowText(string? value) => PublicFacingCopyHumanizer.Clean(value);",
        "@PublicNowText(Model.ReleaseExperience.ReleaseNotesSummary)",
        "@PublicNowText(Model.ReleaseExperience.KnownIssuesLabel)",
        "@PublicNowText(Model.ReleaseExperience.UpdatePostureSummary)",
        "@PublicSurfaceStatus.DisplayLabel(card.Card.Badge)",
        "<h3>@PublicNowText(card.Card.Title)</h3>",
        "<p>@PublicNowText(card.Card.Summary)</p>",
        "@PublicNowText(card.Card.ProofNote)",
        "@PublicNowText(card.Action.Label)",
        "@PublicNowText(overlay.Title)",
    ):
        assert expected in now

    for forbidden in (
        "<p>@Model.ReleaseExperience.ReleaseNotesSummary</p>",
        ">@Model.ReleaseExperience.KnownIssuesLabel</a>",
        "@PublicFacingCopyHumanizer.Clean(Model.ReleaseExperience.UpdatePostureSummary)",
        "<span class=\"tag\">@card.Card.Badge</span>",
        "<h3>@card.Card.Title</h3>",
        "<p>@card.Card.Summary</p>",
        ">@card.Action.Label</a>",
        "<span>@overlay.Title</span>",
    ):
        assert forbidden not in now


def test_shared_public_panels_clean_dynamic_copy_before_rendering() -> None:
    privacy = read("Chummer.Run.Api/Views/Shared/_PrivacyBoundaryPanel.cshtml")
    signed_in = read("Chummer.Run.Api/Views/Shared/_SignedInTrustStatusPanel.cshtml")
    pulse_panel = read("Chummer.Run.Api/Views/Shared/_PublicTrustPulsePanel.cshtml")
    pulse_body = read("Chummer.Run.Api/Views/Shared/_PublicTrustPulseBody.cshtml")
    combined = "\n".join((privacy, signed_in, pulse_panel, pulse_body))

    for expected in (
        "static string PublicPrivacyText(string? value) => PublicFacingCopyHumanizer.Clean(value);",
        "static string PublicSignedInTrustText(string? value) => PublicFacingCopyHumanizer.Clean(value);",
        "static string PublicTrustPulseText(string? value) => PublicFacingCopyHumanizer.Clean(value);",
        "@PublicPrivacyText(Model.Heading)",
        "@PublicPrivacyText(Model.Summary)",
        "@PublicPrivacyText(Model.PrimaryAction.Label)",
        "@PublicPrivacyText(domain.RetentionSummary)",
        "@PublicPrivacyText(rule.BlockedSummary)",
        "@PublicSignedInTrustText(Model.Heading)",
        "@PublicSignedInTrustText(Model.PrimaryAction.Label)",
        "@PublicSignedInTrustText(row.Label)",
        "@PublicTrustPulseText(Model.Heading)",
        "@PublicTrustPulseText(Model.PrimaryAction.Label)",
        "@PublicTrustPulseText(Model.Summary)",
        "@PublicTrustPulseText(row.Label)",
    ):
        assert expected in combined

    for forbidden in (
        "<h2>@Model.Heading</h2>",
        "<p>@Model.Summary</p>",
        ">@Model.PrimaryAction.Label</a>",
        ">@Model.SecondaryAction.Label</a>",
        "<span>@item</span>",
        "<span>@row.Label</span>",
        "<span class=\"tag\">@domain.Owner</span>",
        "<h3>@domain.Label</h3>",
        "@domain.RetentionSummary",
        "@domain.RedactionSummary",
        "@rule.BlockedSummary",
    ):
        assert forbidden not in combined


def test_public_detail_page_uses_limited_detail_instead_of_review_process_copy() -> None:
    shelf = read("Chummer.Run.Api/Views/PublicLanding/Shelf.cshtml")

    for forbidden in (
        "Limited public wording",
        "limited public wording",
        "public comparison language",
        "one more review pass",
        "Public parity claims remain",
        "review-required",
    ):
        assert forbidden not in shelf

    assert "Shared publications with limited detail" in shelf
    assert "shorter public summary" in shelf
    assert "Broader comparisons return when they are useful and current." in shelf


def test_publication_detail_page_uses_plain_labels() -> None:
    publication = read("Chummer.Run.Api/Views/PublicLanding/PublicCreatorPublication.cshtml")

    for forbidden in (
        "Limited public state",
        "Route:",
        "Known issues nearby",
        "No fake build path",
        "No auth wall for discovery",
        "Current desktop coverage still keeps this public wording limited.",
        "Trust</span>",
        "Lineage</span>",
        "supporting detail",
    ):
        assert forbidden not in publication

    assert "Limited detail" in publication
    assert "Page: @routeStateLabel" in publication
    assert "ViewData[\"Title\"] = PublicPublicationText(Model.Publication.Title)" in publication
    assert "@PublicPublicationText(Model.Publication.Title)" in publication
    assert "@PublicPublicationText(Model.Publication.Summary)" in publication
    assert "@PublicPublicationText(Model.TrustPulse.RouteGuardSummary)" in publication
    assert "ViewData[\"Title\"] = Model.Publication.Title" not in publication
    assert "@Model.Publication.Title" not in publication
    assert "@Model.Publication.Summary" not in publication
    assert "@Model.TrustPulse.RouteGuardSummary" not in publication
    assert "Install notes nearby" in publication
    assert "Clear install path" in publication
    assert "Public discovery stays open" in publication
    assert "Some desktop work is still open, so this public summary stays short." in publication
    assert "Status</span>" in publication
    assert "History</span>" in publication
    assert "related detail" in publication


def test_faction_workspace_uses_page_language_instead_of_route_language() -> None:
    workspace = read("Chummer.Run.Api/Views/PublicLanding/LedgerFactionWorkspace.cshtml")

    for forbidden in (
        "Authenticated route",
        "Public route stays separate",
        "Current signed-in workspace.",
        "public Ledger routes",
        "authenticated campaign routes",
        "Public Ledger routes",
        "signed-in faction routes",
        "faction overlay route",
    ):
        assert forbidden not in workspace

    assert "Signed-in page" in workspace
    assert "Public page stays separate" in workspace
    assert "Current workspace." in workspace
    assert "public Ledger pages" in workspace
    assert "signed-in campaign pages" in workspace
    assert "Public Ledger pages" in workspace
    assert "signed-in faction pages" in workspace
    assert "private lore overlay" in workspace


def test_signed_in_ledger_pages_use_page_and_path_language() -> None:
    account_home = read("Chummer.Run.Api/Views/PublicLanding/LedgerAccountHome.cshtml")
    notifications = read("Chummer.Run.Api/Views/PublicLanding/LedgerNotifications.cshtml")
    ledger = read("Chummer.Run.Api/Views/PublicLanding/Ledger.cshtml")
    advisory = read("Chummer.Run.Api/Views/PublicLanding/LedgerAdvisory.cshtml")
    onboarding = read("Chummer.Run.Api/Views/PublicLanding/LedgerOnboarding.cshtml")
    combined = "\n".join((account_home, notifications, ledger, advisory, onboarding))

    for forbidden in (
        "signed-in route",
        "Open mail-backed route",
        "route-backed world state",
        "one Chummer route",
        "inbox route",
        "public globe route",
        "Open watch route",
        "Major and challenger routes",
        "Current world-turn packet",
    ):
        assert forbidden not in combined

    assert "signed-in page" in account_home
    assert "Open mail-backed page" in account_home
    assert "current world state" in notifications
    assert "one Chummer path" in notifications
    assert "Use the inbox as the Table Pulse Live entry point" in notifications
    assert "public globe page" in ledger
    assert "Open watch page" in ledger
    assert "Current turn details" in account_home
    assert "signed-in page that mails and inbox items point back to" in advisory
    assert "Major and challenger paths" in onboarding


def test_faction_builder_and_promo_use_page_language_instead_of_route_language() -> None:
    faction_create = read("Chummer.Run.Api/Views/PublicLanding/LedgerFactionCreate.cshtml")
    faction_promo = read("Chummer.Run.Api/Views/PublicLanding/LedgerFactionPromo.cshtml")
    combined = "\n".join((faction_create, faction_promo))

    for forbidden in (
        "riskier route",
        "route-backed",
        "Every faction video route",
    ):
        assert forbidden not in combined

    assert "riskier start" in faction_create
    assert "Every faction video page includes video files" in faction_promo


def test_package_pages_use_page_language_instead_of_route_language() -> None:
    package_detail = read("Chummer.Run.Api/Views/PublicLanding/PackageDetail.cshtml")
    package_receipt = read("Chummer.Run.Api/Views/PublicLanding/PackageReceipt.cshtml")
    combined = "\n".join((package_detail, package_receipt))

    for forbidden in (
        "Next route",
        "Return to the package route",
        "package route.",
    ):
        assert forbidden not in combined

    assert "Next step" in package_receipt
    assert "Return to the package page" in package_receipt
    assert "Package history stays attached to this package page." in package_detail


def test_mobile_helper_and_anarchy_pages_use_page_and_export_language() -> None:
    mobile = read("Chummer.Run.Api/Views/PublicLanding/MobileProjection.cshtml")
    knowledge = read("Chummer.Run.Api/Views/PublicLanding/KnowledgeFabric.cshtml")
    anarchy = read("Chummer.Run.Api/Views/PublicLanding/Anarchy.cshtml")
    combined = "\n".join((mobile, knowledge, anarchy))

    for forbidden in (
        "app route",
        "continuity route",
        "routes converge",
        "This route keeps rule answers",
        "Chummer packet, not book text",
        "This route reads Chummer dispatches",
        "portable packet",
        "Portable runner packet",
        "provenance attached",
    ):
        assert forbidden not in combined

    assert "app page, manifest, and service worker" in mobile
    assert "continuity page" in mobile
    assert "entry points meet in one shell" in mobile
    assert "This page keeps rule answers short" in knowledge
    assert "Chummer export, not book text" in anarchy
    assert "This page reads Chummer dispatches" in anarchy
    assert "Chummer owns the portable export" in anarchy
    assert "Portable runner export" in anarchy
