from __future__ import annotations

import importlib.util
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MODULE_PATH = ROOT / "scripts" / "verify_public_copy_leak_gate.py"


def load_module():
    spec = importlib.util.spec_from_file_location("verify_public_copy_leak_gate", MODULE_PATH)
    assert spec is not None
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_public_copy_leak_gate_blocks_visible_ai_generated_language():
    module = load_module()

    text = "This AI-generated workflow was generated by AI from a prompt engineered source packet."
    hits = module.forbidden_hits(text)

    assert any("generated by AI" in hit for hit in hits)
    assert any("AI-generated" in hit for hit in hits)
    assert any("prompt engineered" in hit for hit in hits)


def test_public_copy_leak_gate_allows_minimal_human_product_copy():
    module = load_module()

    hits = module.forbidden_hits("Build and maintain Shadowrun characters without losing details between sessions.")

    assert hits == []


def test_visible_text_includes_accessibility_labels_and_alt_text():
    module = load_module()

    text = module.visible_text(
        '<main><img alt="Proof gallery"><button aria-label="AI assistant">Open</button><a title="provider route">More</a></main>'
    )

    assert "Proof gallery" in text
    assert "AI assistant" in text
    assert "provider route" in text


def test_minimal_public_routes_block_ai_proof_and_campaign_city_language():
    module = load_module()

    text = "Alice and the assistant can open Black Ledger proof receipts from the operator artifact lane after validation checks."
    hits = module.minimal_route_forbidden_hits(text)

    assert any("Alice" in hit for hit in hits)
    assert any("assistant" in hit for hit in hits)
    assert any("Black Ledger" in hit for hit in hits)
    assert any("proof" in hit for hit in hits)
    assert any("receipt" in hit for hit in hits)
    assert any("operator" in hit for hit in hits)
    assert any("artifact" in hit for hit in hits)
    assert any("validation" in hit for hit in hits)
    assert any("checks" in hit for hit in hits)
    assert any("lane" in hit for hit in hits)


def test_minimal_route_detection_keeps_special_routes_out_of_first_visit_tier():
    module = load_module()

    assert module.is_minimal_public_route("/")
    assert module.is_minimal_public_route("/downloads")
    assert module.is_minimal_public_route("/feedback")
    assert module.is_minimal_public_route("/login?next=%2Faccount%2Faccess")
    assert not module.is_minimal_public_route("/ledger")
    assert not module.is_minimal_public_route("/horizons")


def test_route_result_fails_when_minimal_route_contains_strict_forbidden_copy():
    module = load_module()

    result = module.RouteResult(
        route="/",
        url="https://example.invalid/",
        status_code=200,
        success=False,
        forbidden_hits=[],
        minimal_route=True,
        minimal_forbidden_hits=[r"\bAI\b"],
        detail="minimal public route contains AI, proof, campaign-city, provider, or internal workflow wording",
    )
    payload = module.build_payload("https://example.invalid", [result])

    assert payload["status"] == "fail"
    assert payload["routes"][0]["minimal_route"] is True
    assert payload["routes"][0]["minimal_forbidden_hits"] == [r"\bAI\b"]
