from __future__ import annotations

import importlib.util
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MODULE_PATH = ROOT / "scripts" / "verify_public_copy_leak_gate.py"
FORBIDDEN_SCAN_MODULE_PATH = ROOT / "scripts" / "public_forbidden_string_scan.py"


def load_module():
    spec = importlib.util.spec_from_file_location("verify_public_copy_leak_gate", MODULE_PATH)
    assert spec is not None
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def load_forbidden_scan_module():
    scripts_dir = str(ROOT / "scripts")
    if scripts_dir not in sys.path:
        sys.path.insert(0, scripts_dir)
    spec = importlib.util.spec_from_file_location("public_forbidden_string_scan", FORBIDDEN_SCAN_MODULE_PATH)
    assert spec is not None
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_public_copy_leak_gate_blocks_visible_ai_generated_language():
    module = load_module()

    text = "This AI-generated workflow was generated by AI from a prompt engineered source packet."
    hits = module.forbidden_hits(text)

    assert any("generated by AI" in hit for hit in hits)
    assert any("AI-generated" in hit for hit in hits)
    assert any("prompt engineered" in hit for hit in hits)


def test_public_copy_leak_gate_blocks_internal_decision_and_status_terms():
    module = load_module()

    text = "Product Governor release-backed proof-bound package truth should never be visible copy."
    hits = module.forbidden_hits(text)

    assert any("Product Governor" in hit for hit in hits)
    assert any("release-backed" in hit for hit in hits)
    assert any("proof-bound" in hit for hit in hits)
    assert any("package truth" in hit for hit in hits)


def test_public_copy_leak_gate_allows_minimal_human_product_copy():
    module = load_module()

    hits = module.forbidden_hits("Build and maintain Shadowrun characters without losing details between sessions.")

    assert hits == []


def test_visible_text_includes_accessibility_labels_and_alt_text():
    module = load_module()

    text = module.visible_text(
        '<main><img alt="Proof gallery"><button aria-label="AI assistant">Open</button><a title="provider route">More</a></main>'
    )

    assert "Proof gallery" in text
    assert "AI assistant" in text
    assert "provider route" in text


def test_minimal_public_routes_block_ai_proof_and_campaign_city_language():
    module = load_module()

    text = "Alice and the assistant can open Black Ledger proof receipts from the operator artifact lane after validation checks."
    hits = module.minimal_route_forbidden_hits(text)

    assert any("Alice" in hit for hit in hits)
    assert any("assistant" in hit for hit in hits)
    assert any("Black Ledger" in hit for hit in hits)
    assert any("proof" in hit for hit in hits)
    assert any("receipt" in hit for hit in hits)
    assert any("operator" in hit for hit in hits)
    assert any("artifact" in hit for hit in hits)
    assert any("validation" in hit for hit in hits)
    assert any("checks" in hit for hit in hits)
    assert any("lane" in hit for hit in hits)


def test_minimal_public_routes_allow_frontdoor_release_posture_copy():
    module = load_module()

    hits = module.minimal_route_forbidden_hits("Current public lane: Preview. Review required.")

    assert hits == []


def test_minimal_public_routes_allow_preview_review_required_copy():
    module = load_module()

    hits = module.minimal_route_forbidden_hits("Preview build. Review required.")

    assert hits == []


def test_minimal_route_detection_keeps_special_routes_out_of_first_visit_tier():
    module = load_module()

    assert module.is_minimal_public_route("/")
    assert module.is_minimal_public_route("/downloads")
    assert module.is_minimal_public_route("/contact")
    assert module.is_minimal_public_route("/login?next=%2Faccount%2Faccess")
    assert not module.is_minimal_public_route("/feedback")
    assert not module.is_minimal_public_route("/ledger")
    assert not module.is_minimal_public_route("/horizons")


def test_route_result_fails_when_minimal_route_contains_strict_forbidden_copy():
    module = load_module()
    detail = "first-visit page contains specialist feature names, internal process wording, or lab wording"

    result = module.RouteResult(
        route="/",
        url="https://example.invalid/",
        status_code=200,
        success=False,
        forbidden_hits=[],
        minimal_route=True,
        minimal_forbidden_hits=[r"\bAI\b"],
        detail=detail,
    )
    payload = module.build_payload("https://example.invalid", [result])

    assert payload["status"] == "fail"
    assert payload["routes"][0]["minimal_route"] is True
    assert payload["routes"][0]["minimal_forbidden_hits"] == [r"\bAI\b"]
    assert "AI, proof" not in detail
    assert "artifact" not in detail
    assert "lane" not in detail


def test_participation_external_redirect_fails_because_participate_is_first_party():
    module = load_module()

    class FakeResponse:
        status_code = 302
        text = "ProductLift"
        headers = {"Location": "https://chummer6.productlift.dev"}

    class FakeSession:
        def get(self, url: str, timeout: int, allow_redirects: bool):
            assert url == "https://chummer.run/participate"
            assert timeout == module.DEFAULT_TIMEOUT_SECONDS
            assert allow_redirects is False
            return FakeResponse()

    result = module.verify_route(FakeSession(), "https://chummer.run", "/participate")

    assert result.success is False
    assert result.redirect_external is True
    assert result.redirect_url == "https://chummer6.productlift.dev"
    assert result.detail == "route redirects outside Chummer from an unapproved public path"
    assert result.forbidden_hits == []


def test_public_copy_leak_gate_scans_participate_board_route():
    module = load_module()

    assert "/participate" in module.DEFAULT_ROUTES
    assert "/partizipate" in module.DEFAULT_ROUTES
    assert "/participate/board" in module.DEFAULT_ROUTES
    assert "/contact" in module.DEFAULT_ROUTES
    assert module.forbidden_hits("ProductLift Log in Sign up Could not load posts")


def test_unapproved_external_redirect_fails_public_copy_gate():
    module = load_module()

    class FakeResponse:
        status_code = 302
        text = ""
        headers = {"Location": "https://example.invalid/outside"}

    class FakeSession:
        def get(self, url: str, timeout: int, allow_redirects: bool):
            assert allow_redirects is False
            return FakeResponse()

    result = module.verify_route(FakeSession(), "https://chummer.run", "/downloads")

    assert result.success is False
    assert result.redirect_external is True
    assert result.detail == "route redirects outside Chummer from an unapproved public path"


def test_verify_route_retries_transient_transport_failure():
    module = load_module()

    class FakeResponse:
        status_code = 200
        text = "<main>Build and maintain Shadowrun characters.</main>"
        headers = {}

    class FakeSession:
        def __init__(self) -> None:
            self.calls = 0

        def get(self, url: str, timeout: int, allow_redirects: bool):
            self.calls += 1
            if self.calls == 1:
                raise TimeoutError("timed out once")
            return FakeResponse()

    session = FakeSession()
    result = module.verify_route(session, "https://chummer.run", "/")

    assert session.calls == 2
    assert result.success is True
    assert result.detail is None


def test_verify_route_uses_explicit_timeout_override():
    module = load_module()

    class FakeResponse:
        status_code = 200
        text = "<main>Build and maintain Shadowrun characters.</main>"
        headers = {}

    class FakeSession:
        def __init__(self) -> None:
            self.seen_timeout = None

        def get(self, url: str, timeout: int, allow_redirects: bool):
            self.seen_timeout = timeout
            return FakeResponse()

    session = FakeSession()
    result = module.verify_route(session, "https://chummer.run", "/", timeout_seconds=33)

    assert result.success is True
    assert session.seen_timeout == 33


def test_provider_scanner_uses_visible_html_text_not_script_or_href_details():
    module = load_forbidden_scan_module()

    markup = """
    <main>
      <a href="https://chummer6.productlift.dev">Participate</a>
      <script>window.clickRankScript = "https://js.clickrank.ai/script";</script>
    </main>
    """

    assert module.scan_text("html", "/", module.visible_text(markup)) == []
    assert module.scan_text("html", "/", module.visible_text("<main>Open ProductLift</main>"))


def test_provider_scanner_checks_participate_board_route():
    module = load_forbidden_scan_module()

    assert "/participate/board" in module.HTML_ROUTES
