import { expect, test } from 'playwright/test';
import { writeJsonArtifact, writeMarkdownArtifact } from './ux-artifacts';

const baseUrl = process.env.BASE_URL?.trim() || 'https://chummer.run';

const routes = [
  { path: '/', schemaType: 'SoftwareApplication' },
  { path: '/downloads', schemaType: 'SoftwareApplication' },
  { path: '/what-is-chummer', schemaType: 'SoftwareApplication' },
  { path: '/status', schemaType: 'WebPage' },
  { path: '/help', schemaType: 'WebPage' },
] as const;

test('ClickRank and NeuronWriter optimization stays metadata-only and minimal', async ({ page }) => {
  test.setTimeout(120000);
  const failures: string[] = [];
  const results: Array<Record<string, unknown>> = [];

  for (const route of routes) {
    await page.goto(`${baseUrl}${route.path}`, { waitUntil: 'domcontentloaded' });

    const canonical = await page.locator('link[rel="canonical"]').getAttribute('href');
    const expectedCanonical = `https://chummer.run${route.path === '/' ? '' : route.path}`;
    if (canonical !== expectedCanonical) {
      failures.push(`${route.path}: canonical was ${canonical ?? '<missing>'}`);
    }

    const description = (await page.locator('meta[name="description"]').getAttribute('content')) || '';
    if (description.length < 35 || description.length > 160) {
      failures.push(`${route.path}: description length ${description.length} is outside the minimal search range`);
    }

    const robots = (await page.locator('meta[name="robots"]').getAttribute('content')) || '';
    if (!robots.includes('index') || !robots.includes('follow')) {
      failures.push(`${route.path}: robots policy is not indexable`);
    }

    const schemaRaw = await page.locator('script[type="application/ld+json"]').first().textContent();
    if (!schemaRaw) {
      failures.push(`${route.path}: schema is missing`);
    } else {
      const schema = JSON.parse(schemaRaw);
      if (schema['@type'] !== route.schemaType) {
        failures.push(`${route.path}: schema type was ${schema['@type']}`);
      }
      if (String(schema.operatingSystem || '').toLowerCase().includes('mac')) {
        failures.push(`${route.path}: schema still advertises macOS as a public installer lane`);
      }
    }

    const bodyText = ((await page.locator('body').textContent()) || '').replace(/\s+/g, ' ');
    for (const term of ['ClickRank', 'NeuronWriter', 'SEO', 'optimized by', 'generated by AI']) {
      if (bodyText.includes(term)) {
        failures.push(`${route.path}: visible body copy exposes "${term}"`);
      }
    }
    const pageSource = await page.content();
    for (const term of ['data-clickrank-ai', 'clickRankAi', 'public-copy-humanizer']) {
      if (pageSource.includes(term)) {
        failures.push(`${route.path}: page source exposes stale provider marker "${term}"`);
      }
    }

    results.push({
      route: route.path,
      canonical,
      description_length: description.length,
      robots,
      schema_type: route.schemaType,
    });
  }

  const status = failures.length === 0 ? 'pass' : 'fail';
  writeJsonArtifact('MINIMAL_SEO_PROVIDER_PASS.generated.json', {
    generated_at_utc: new Date().toISOString(),
    base_url: baseUrl,
    status,
    verdict: status === 'pass' ? 'MINIMAL_SEO_READY' : 'MINIMAL_SEO_NOT_READY',
    provider_boundary: {
      clickrank: 'public crawl and metadata signal only',
      neuronwriter: 'source-packet copy review only',
      visible_provider_copy: false,
    },
    checks: results,
    failures,
  });

  writeMarkdownArtifact(
    'MINIMAL_SEO_PROVIDER_PASS.md',
    [
      '# Minimal SEO Provider Pass',
      '',
      `- Generated: ${new Date().toISOString()}`,
      `- Base URL: ${baseUrl}`,
      '- Scope: canonical links, schema, descriptions, and provider-name invisibility.',
      '- Boundary: providers may recommend metadata and source-copy changes; pages stay minimal.',
      `- Verdict: ${status === 'pass' ? 'MINIMAL_SEO_READY' : 'MINIMAL_SEO_NOT_READY'}`,
      ...(failures.length > 0 ? ['', '## Failures', '', ...failures.map((failure) => `- ${failure}`)] : []),
    ].join('\n'),
  );

  expect(failures, failures.join('\n')).toEqual([]);
});
