import { expect, test } from 'playwright/test';
import { writeMarkdownArtifact } from './ux-artifacts';

const baseUrl = process.env.BASE_URL?.trim() || 'https://chummer.run';

test('homepage stays within the pre-gold noise budget', async ({ page }) => {
  await page.goto(baseUrl, { waitUntil: 'domcontentloaded' });

  const sections = page.locator('[data-homepage-section]');
  await expect(sections).toHaveCount(4);

  const navLabels = await page.locator('[aria-label="Primary navigation"] a, [aria-label="Primary navigation"] .site-sidebar__current').evaluateAll((items) =>
    items.map((item) => (item.textContent || '').replace(/\s+/g, ' ').trim()).filter(Boolean),
  );
  expect(navLabels).toEqual(['Home', 'Get Chummer', 'Help']);

  const hero = page.locator('[data-homepage-section="hero"]');
  const heroText = (await hero.textContent()) || '';
  expect(heroText.toLowerCase()).not.toContain('proof');
  expect(heroText.toLowerCase()).not.toContain('artifact');
  expect(heroText.toLowerCase()).not.toContain('repo');

  writeMarkdownArtifact(
    'FINAL_PUBLIC_UX_REDESIGN_VERDICT.md',
    [
      '# Final public UX redesign verdict',
      '',
      '- Homepage sections: `4`',
      '- Primary nav: `Home, Get Chummer, Help`',
      '- First-screen proof noise: `0`',
      '- Verdict: `READY`',
    ].join('\n'),
  );
});

test('help page stays practical instead of exposing internal policy language', async ({ page }) => {
  await page.goto(`${baseUrl}/help`, { waitUntil: 'domcontentloaded' });

  const bodyText = ((await page.locator('body').textContent()) || '').replace(/\s+/g, ' ');

  await expect(page.locator('h1')).toContainText('Get help without guessing');
  expect(bodyText).toContain('Choose the right path.');
  expect(bodyText).not.toContain('Provider-backed help');
  expect(bodyText).not.toContain('Retention window');
  expect(bodyText).not.toContain('receipt');
  expect(bodyText).not.toContain('chummer6-hub');
  expect(bodyText).not.toContain('GitHub');
  expect(bodyText).not.toContain('generated by AI');
  expect(bodyText).not.toContain('proof trail');
  expect(bodyText).not.toContain('opaque assistant');
  expect(bodyText).not.toContain('mystery math');
});

test('core public pages do not expose AI or repo-process copy', async ({ page }) => {
  const blockedTerms = [
    'Generated by AI',
    'generated by AI',
    'AI everywhere',
    'proof trail',
    'opaque assistant',
    'mystery math',
    'chummer6-hub',
    'GitHub',
  ];

  for (const path of ['/', '/downloads', '/status', '/help', '/faq', '/contact']) {
    await page.goto(`${baseUrl}${path}`, { waitUntil: 'domcontentloaded' });
    const bodyText = ((await page.locator('body').textContent()) || '').replace(/\s+/g, ' ');

    for (const term of blockedTerms) {
      expect(bodyText, `${path} should not expose "${term}"`).not.toContain(term);
    }
  }
});

test('future ideas keep unfinished campaign layers out of the public path', async ({ page, request }) => {
  await page.goto(`${baseUrl}/horizons`, { waitUntil: 'domcontentloaded' });
  const horizonsText = ((await page.locator('body').textContent()) || '').replace(/\s+/g, ' ');

  expect(horizonsText).not.toContain('Black Ledger');
  expect(horizonsText).not.toContain('Open Black Ledger');
  expect(horizonsText).toContain('Early campaign-city work stays behind the main app');

  const llmsResponse = await request.get(`${baseUrl}/llms.txt`);
  expect(llmsResponse.ok()).toBeTruthy();
  const llmsText = await llmsResponse.text();
  expect(llmsText).not.toContain('/ledger :');
  expect(llmsText).not.toContain('/black-ledger');
  expect(llmsText).not.toContain('Black Ledger');
  expect(llmsText).toContain('/alice : character helper entry');
});
