import { expect, test } from 'playwright/test';
import { writeMarkdownArtifact } from './ux-artifacts';

const baseUrl = process.env.BASE_URL?.trim() || 'https://chummer.run';

test('homepage stays within the pre-gold noise budget', async ({ page }) => {
  test.setTimeout(90_000);

  await page.goto(baseUrl, { waitUntil: 'domcontentloaded' });

  const sections = page.locator('[data-homepage-section]');
  await expect(sections).toHaveCount(1);

  const navLabels = await page.locator('.site-nav a, .site-nav__current').evaluateAll((items) =>
    items.map((item) => (item.textContent || '').replace(/\s+/g, ' ').trim()).filter(Boolean),
  );
  expect(navLabels).toEqual([]);

  const hero = page.locator('[data-homepage-section="hero"]');
  const heroText = (await hero.textContent()) || '';
  expect(heroText.toLowerCase()).not.toContain('proof');
  expect(heroText.toLowerCase()).not.toContain('artifact');
  expect(heroText.toLowerCase()).not.toContain('repo');
  expect(heroText).toContain('Download Chummer');
  expect(heroText).not.toContain('Stable');
  expect(heroText).not.toContain('Nightly');

  writeMarkdownArtifact(
    'FINAL_PUBLIC_UX_REDESIGN_VERDICT.md',
    [
      '# Final public UX redesign verdict',
      '',
      '- Homepage sections: `1`',
      '- Primary nav on landing: `hidden`',
      '- First-screen proof noise: `0`',
      '- Verdict: `READY`',
    ].join('\n'),
  );
});

test('help page stays practical instead of exposing internal policy language', async ({ page }) => {
  await page.goto(`${baseUrl}/help`, { waitUntil: 'domcontentloaded' });

  const bodyText = ((await page.locator('body').textContent()) || '').replace(/\s+/g, ' ');

  await expect(page.locator('h1')).toContainText('What is wrong?');
  expect(bodyText).toContain('Pick the next step');
  expect(bodyText).not.toContain('Pick the problem');
  expect(bodyText).not.toContain('Provider-backed help');
  expect(bodyText).not.toContain('Retention window');
  expect(bodyText).not.toContain('receipt');
  expect(bodyText).not.toContain('chummer6-hub');
  expect(bodyText).not.toContain('GitHub');
  expect(bodyText).not.toContain('generated by AI');
  expect(bodyText).not.toContain('proof trail');
  expect(bodyText).not.toContain('opaque assistant');
  expect(bodyText).not.toContain('mystery math');
});

test('contact page keeps routing and private intake clear without extra ceremony', async ({ page }) => {
  await page.goto(`${baseUrl}/contact`, { waitUntil: 'domcontentloaded' });

  const bodyText = ((await page.locator('body').textContent()) || '').replace(/\s+/g, ' ');

  await expect(page.locator('h1')).toContainText('Contact');
  expect(bodyText).toContain('Discord or private');
  expect(bodyText).toContain('Discord first. Private form if needed.');
  expect(bodyText).toContain('Discord for normal questions. Private form for account or crash details.');
  expect(bodyText).not.toContain('Discord for normal contact. Private form for logs or account details.');
  expect(bodyText).not.toContain('Public ideas go to Participate. Private problems stay here.');
  expect(bodyText).not.toContain('Public requests belong on Participate.');
  expect(bodyText).not.toContain('Choose one');
  expect(bodyText).not.toContain('Discord first. Private form only for logs or account details.');
  expect(bodyText).toContain('One problem per message keeps the reply clear.');
  expect(bodyText).not.toContain('Open the right support case');
  expect(bodyText).not.toContain('Use Participate for ideas and safe public bugs');
  expect(bodyText).not.toContain('Keep one issue per case so the reply stays clear.');
  expect(bodyText).not.toContain('Case-type guide');
  expect(bodyText).not.toContain('Need a different path?');
  expect(bodyText).not.toContain('Safe public feedback should start on the public feedback page');
  expect(bodyText).not.toContain('generated by AI');
  expect(bodyText).not.toContain('proof trail');
});

test('public user pages do not expose AI or repo-process copy', async ({ page, request }, testInfo) => {
  testInfo.setTimeout(90_000);
  const blockedTerms = [
    'AI',
    'ALICE',
    'Alice',
    'Black Ledger',
    'Generated by AI',
    'generated by AI',
    'AI everywhere',
    'proof trail',
    'proof',
    'receipt',
    'opaque assistant',
    'mystery math',
    'chummer6-hub',
    'GitHub',
    'governed',
    'operator',
    'artifact',
  ];
  const blockedSourceTerms = [
    'data-clickrank-ai',
    'clickRankAi',
    'public-copy-humanizer',
    'generated by AI',
    'Generated by AI',
    'AI-generated',
    'AI generated',
  ];

  const participateResponse = await request.get(`${baseUrl}/participate`);
  expect(participateResponse.status()).toBe(200);
  const participateText = await participateResponse.text();
  expect(participateText).toContain('What should Chummer do next?');
  expect(participateText).toContain('Public requests, clear bugs, useful ideas.');
  expect(participateText).not.toContain('data-chummer-board-skin');
  expect(participateText).not.toContain('ProductLift');
  expect(participateText).not.toContain('productlift.dev');

  for (const path of ['/', '/downloads', '/status', '/help', '/faq', '/contact', '/downloads/concierge', '/packages', '/alice', '/roadmap', '/changelog', '/horizons', '/now', '/what-is-chummer']) {
    await page.goto(`${baseUrl}${path}`, { waitUntil: 'domcontentloaded' });
    const bodyText = ((await page.locator('body').textContent()) || '').replace(/\s+/g, ' ');
    const pageSource = await page.content();

    for (const term of blockedTerms) {
      expect(bodyText, `${path} should not expose "${term}"`).not.toContain(term);
    }
    for (const term of blockedSourceTerms) {
      expect(pageSource, `${path} source should not expose "${term}"`).not.toContain(term);
    }
  }
});

test('direct character helper route stays private-preview and human-readable', async ({ page }) => {
  await page.goto(`${baseUrl}/alice`, { waitUntil: 'domcontentloaded' });
  const bodyText = ((await page.locator('body').textContent()) || '').replace(/\s+/g, ' ');

  await expect(page.locator('h1')).toContainText('Character help');
  expect(bodyText).toContain('Use this page only when you want help before returning to Chummer.');
  for (const term of ['ALICE', 'Build Ghost', 'build-ghost', 'receipt', 'proof', 'artifact', 'governed', 'operator']) {
    expect(bodyText, `/alice should not expose "${term}"`).not.toContain(term);
  }
});

test('core public pages stay inside a minimal interaction budget', async ({ page }) => {
  test.setTimeout(90_000);
  const budgets = [
    { path: '/', maxWords: 180, maxLinks: 10, maxButtons: 5, maxSections: 4 },
    { path: '/downloads', maxWords: 140, maxLinks: 8, maxButtons: 6, maxSections: 4 },
    { path: '/status', maxWords: 110, maxLinks: 5, maxButtons: 3, maxSections: 3 },
    { path: '/help', maxWords: 450, maxLinks: 16, maxButtons: 3, maxSections: 3 },
    { path: '/contact', maxWords: 430, maxLinks: 14, maxButtons: 6, maxSections: 4 },
    { path: '/account/billing', maxWords: 190, maxLinks: 4, maxButtons: 3, maxSections: 2 },
    { path: '/roadmap', maxWords: 420, maxLinks: 12, maxButtons: 6, maxSections: 3 },
    { path: '/what-is-chummer', maxWords: 130, maxLinks: 4, maxButtons: 3, maxSections: 3 },
    { path: '/downloads/concierge', maxWords: 260, maxLinks: 7, maxButtons: 2, maxSections: 4 },
  ] as const;

  const blockedMainPathTerms = ['Black Ledger', 'generated by AI', 'proof', 'receipt', 'artifact', 'operator', 'governed'];

  for (const budget of budgets) {
    await page.goto(`${baseUrl}${budget.path}`, { waitUntil: 'domcontentloaded' });

    const metrics = await page.evaluate(() => {
      const main = document.querySelector('main') || document.body;
      const text = (main.textContent || '').replace(/\s+/g, ' ').trim();
      return {
        text,
        wordCount: text.length === 0 ? 0 : text.split(/\s+/).length,
        linkCount: main.querySelectorAll('a').length,
        buttonCount: main.querySelectorAll('a.button-like, button').length,
        sectionCount: main.querySelectorAll('section').length,
      };
    });

    expect(metrics.wordCount, `${budget.path} word count`).toBeLessThanOrEqual(budget.maxWords);
    expect(metrics.linkCount, `${budget.path} link count`).toBeLessThanOrEqual(budget.maxLinks);
    expect(metrics.buttonCount, `${budget.path} action count`).toBeLessThanOrEqual(budget.maxButtons);
    expect(metrics.sectionCount, `${budget.path} section count`).toBeLessThanOrEqual(budget.maxSections);

    for (const term of blockedMainPathTerms) {
      expect(metrics.text, `${budget.path} should keep "${term}" off the main public path`).not.toContain(term);
    }
  }
});

test('future ideas keep unfinished campaign layers out of the public path', async ({ page, request }) => {
  await page.goto(`${baseUrl}/horizons`, { waitUntil: 'domcontentloaded' });
  const horizonsText = ((await page.locator('body').textContent()) || '').replace(/\s+/g, ' ');

  expect(horizonsText).not.toContain('Black Ledger');
  expect(horizonsText).not.toContain('Open Black Ledger');
  expect(horizonsText).toContain('Future work stays behind the main app');
  expect(horizonsText).toContain('Not the front door');
  expect(horizonsText.toLowerCase()).not.toContain('horizon');
  expect(horizonsText).not.toContain('Watch');
  expect(horizonsText).not.toContain('deep dive');

  const llmsResponse = await request.get(`${baseUrl}/llms.txt`);
  expect(llmsResponse.ok()).toBeTruthy();
  const llmsText = await llmsResponse.text();
  expect(llmsText).not.toContain('/ledger :');
  expect(llmsText).not.toContain('/black-ledger');
  expect(llmsText).not.toContain('Black Ledger');
  expect(llmsText).not.toContain('/alice');
  expect(llmsText).not.toContain('/table-pulse');
  expect(llmsText).not.toContain('/quicksilver');
  expect(llmsText).not.toContain('/local-co-processor');

  const aiResponse = await request.get(`${baseUrl}/ai.txt`);
  expect(aiResponse.ok()).toBeTruthy();
  const aiText = await aiResponse.text();
  expect(aiText).not.toContain('/alice');
  expect(aiText).not.toContain('/table-pulse');
  expect(aiText).not.toContain('/quicksilver');
  expect(aiText).not.toContain('/local-co-processor');
  expect(aiText).not.toContain('AI helper');

  const sitemapResponse = await request.get(`${baseUrl}/sitemap.xml`);
  expect(sitemapResponse.ok()).toBeTruthy();
  const sitemapText = await sitemapResponse.text();
  expect(sitemapText).not.toContain('/ledger');
  expect(sitemapText).not.toContain('/alice');
  expect(sitemapText).not.toContain('/participate');

  const robotsResponse = await request.get(`${baseUrl}/robots.txt?public-route-guard=1`);
  expect(robotsResponse.ok()).toBeTruthy();
  const robotsText = await robotsResponse.text();
  for (const path of ['/alice', '/ledger', '/table-pulse', '/quicksilver', '/local-co-processor', '/karma-forge']) {
    expect(robotsText).toContain(`Disallow: ${path}`);
  }
  for (const path of ['/participate', '/participate/', '/participate', '/participate/']) {
    expect(robotsText).not.toContain(`Disallow: ${path}`);
  }
});

test('downloads concierge reads like instant support, not internal governance', async ({ page }) => {
  await page.goto(`${baseUrl}/downloads/concierge`, { waitUntil: 'domcontentloaded' });
  const bodyText = ((await page.locator('body').textContent()) || '').replace(/\s+/g, ' ');

  expect(bodyText).toContain('Answer first. Show the path. Fix or report.');
  for (const term of [
    'Wrapper status',
    'Proof',
    'receipt',
    'bounded handoff',
    'first-party boundary',
    'mint',
    'booking',
    'setup clinic',
    'help session',
    'call',
    'Lunacal',
  ]) {
    expect(bodyText, `/downloads/concierge should not expose "${term}"`).not.toContain(term);
  }
});

test('public feature detail pages stay compact and human-facing', async ({ page }) => {
  const paths = ['/artifacts/explanation-receipt-trail', '/artifacts/current-preview-build'] as const;
  const blockedTerms = ['AI', 'ALICE', 'Alice', 'Black Ledger', 'proof', 'receipt', 'artifact', 'operator', 'governed'];

  for (const path of paths) {
    await page.goto(`${baseUrl}${path}`, { waitUntil: 'domcontentloaded' });
    const metrics = await page.evaluate(() => {
      const main = document.querySelector('main') || document.body;
      const text = (main.textContent || '').replace(/\s+/g, ' ').trim();
      return {
        text,
        wordCount: text.length === 0 ? 0 : text.split(/\s+/).length,
        linkCount: main.querySelectorAll('a').length,
        buttonCount: main.querySelectorAll('a.button-like, button').length,
        sectionCount: main.querySelectorAll('section').length,
      };
    });

    expect(metrics.wordCount, `${path} word count`).toBeLessThanOrEqual(260);
    expect(metrics.linkCount, `${path} link count`).toBeLessThanOrEqual(6);
    expect(metrics.buttonCount, `${path} action count`).toBeLessThanOrEqual(3);
    expect(metrics.sectionCount, `${path} section count`).toBeLessThanOrEqual(3);
    for (const term of blockedTerms) {
      expect(metrics.text, `${path} should not expose "${term}"`).not.toContain(term);
    }
  }
});

test('unfinished campaign city route stays hidden from the public roadmap path', async ({ page }) => {
  await page.goto(`${baseUrl}/roadmap/black-ledger`, { waitUntil: 'domcontentloaded' });
  expect(new URL(page.url()).pathname).toBe('/horizons');
  const bodyText = ((await page.locator('body').textContent()) || '').replace(/\s+/g, ' ');
  expect(bodyText).toContain('Not the front door');
  expect(bodyText).not.toContain('Black Ledger');
  expect(bodyText).not.toContain('Open Black Ledger');
  expect(bodyText).not.toContain('command map');
});
