import { expect, test } from 'playwright/test';
import { writeMarkdownArtifact } from './ux-artifacts';

const baseUrl = process.env.BASE_URL?.trim() || 'https://chummer.run';

test('homepage stays within the pre-gold noise budget', async ({ page }) => {
  await page.goto(baseUrl, { waitUntil: 'domcontentloaded' });

  const sections = page.locator('[data-homepage-section]');
  await expect(sections).toHaveCount(4);

  const navLabels = await page.locator('[aria-label="Primary navigation"] a, [aria-label="Primary navigation"] .site-sidebar__current').evaluateAll((items) =>
    items.map((item) => (item.textContent || '').replace(/\s+/g, ' ').trim()).filter(Boolean),
  );
  expect(navLabels).toEqual(['Home', 'Get Chummer', 'Help']);

  const hero = page.locator('[data-homepage-section="hero"]');
  const heroText = (await hero.textContent()) || '';
  expect(heroText.toLowerCase()).not.toContain('proof');
  expect(heroText.toLowerCase()).not.toContain('artifact');
  expect(heroText.toLowerCase()).not.toContain('repo');
  expect(heroText).toContain('Stable');
  expect(heroText).toContain('Nightly');

  writeMarkdownArtifact(
    'FINAL_PUBLIC_UX_REDESIGN_VERDICT.md',
    [
      '# Final public UX redesign verdict',
      '',
      '- Homepage sections: `4`',
      '- Primary nav: `Home, Get Chummer, Help`',
      '- First-screen proof noise: `0`',
      '- Verdict: `READY`',
    ].join('\n'),
  );
});

test('help page stays practical instead of exposing internal policy language', async ({ page }) => {
  await page.goto(`${baseUrl}/help`, { waitUntil: 'domcontentloaded' });

  const bodyText = ((await page.locator('body').textContent()) || '').replace(/\s+/g, ' ');

  await expect(page.locator('h1')).toContainText('Get help without guessing');
  expect(bodyText).toContain('Choose the right path.');
  expect(bodyText).not.toContain('Provider-backed help');
  expect(bodyText).not.toContain('Retention window');
  expect(bodyText).not.toContain('receipt');
  expect(bodyText).not.toContain('chummer6-hub');
  expect(bodyText).not.toContain('GitHub');
  expect(bodyText).not.toContain('generated by AI');
  expect(bodyText).not.toContain('proof trail');
  expect(bodyText).not.toContain('opaque assistant');
  expect(bodyText).not.toContain('mystery math');
});

test('public user pages do not expose AI or repo-process copy', async ({ page }) => {
  const blockedTerms = [
    'AI',
    'ALICE',
    'Alice',
    'Black Ledger',
    'Generated by AI',
    'generated by AI',
    'AI everywhere',
    'proof trail',
    'proof',
    'receipt',
    'opaque assistant',
    'mystery math',
    'chummer6-hub',
    'GitHub',
    'governed',
    'operator',
    'artifact',
  ];

  for (const path of ['/', '/downloads', '/status', '/help', '/faq', '/contact', '/downloads/concierge', '/packages', '/alice', '/roadmap', '/changelog', '/horizons']) {
    await page.goto(`${baseUrl}${path}`, { waitUntil: 'domcontentloaded' });
    const bodyText = ((await page.locator('body').textContent()) || '').replace(/\s+/g, ' ');

    for (const term of blockedTerms) {
      expect(bodyText, `${path} should not expose "${term}"`).not.toContain(term);
    }
  }
});

test('direct character helper route stays private-preview and human-readable', async ({ page }) => {
  await page.goto(`${baseUrl}/alice`, { waitUntil: 'domcontentloaded' });
  const bodyText = ((await page.locator('body').textContent()) || '').replace(/\s+/g, ' ');

  await expect(page.locator('h1')).toContainText('Character helper');
  expect(bodyText).toContain('This preview is kept off the main public path');
  for (const term of ['ALICE', 'Build Ghost', 'build-ghost', 'receipt', 'proof', 'artifact', 'governed', 'operator']) {
    expect(bodyText, `/alice should not expose "${term}"`).not.toContain(term);
  }
});

test('core public pages stay inside a minimal interaction budget', async ({ page }) => {
  const budgets = [
    { path: '/', maxWords: 180, maxLinks: 10, maxButtons: 5, maxSections: 4 },
    { path: '/downloads', maxWords: 140, maxLinks: 8, maxButtons: 6, maxSections: 4 },
    { path: '/status', maxWords: 110, maxLinks: 5, maxButtons: 3, maxSections: 3 },
    { path: '/help', maxWords: 450, maxLinks: 16, maxButtons: 3, maxSections: 3 },
    { path: '/what-is-chummer', maxWords: 130, maxLinks: 4, maxButtons: 3, maxSections: 3 },
    { path: '/downloads/concierge', maxWords: 260, maxLinks: 7, maxButtons: 2, maxSections: 4 },
  ] as const;

  const blockedMainPathTerms = ['Black Ledger', 'generated by AI', 'proof', 'receipt', 'artifact', 'operator', 'governed'];

  for (const budget of budgets) {
    await page.goto(`${baseUrl}${budget.path}`, { waitUntil: 'domcontentloaded' });

    const metrics = await page.evaluate(() => {
      const main = document.querySelector('main') || document.body;
      const text = (main.textContent || '').replace(/\s+/g, ' ').trim();
      return {
        text,
        wordCount: text.length === 0 ? 0 : text.split(/\s+/).length,
        linkCount: main.querySelectorAll('a').length,
        buttonCount: main.querySelectorAll('a.button-like, button').length,
        sectionCount: main.querySelectorAll('section').length,
      };
    });

    expect(metrics.wordCount, `${budget.path} word count`).toBeLessThanOrEqual(budget.maxWords);
    expect(metrics.linkCount, `${budget.path} link count`).toBeLessThanOrEqual(budget.maxLinks);
    expect(metrics.buttonCount, `${budget.path} action count`).toBeLessThanOrEqual(budget.maxButtons);
    expect(metrics.sectionCount, `${budget.path} section count`).toBeLessThanOrEqual(budget.maxSections);

    for (const term of blockedMainPathTerms) {
      expect(metrics.text, `${budget.path} should keep "${term}" off the main public path`).not.toContain(term);
    }
  }
});

test('future ideas keep unfinished campaign layers out of the public path', async ({ page, request }) => {
  await page.goto(`${baseUrl}/horizons`, { waitUntil: 'domcontentloaded' });
  const horizonsText = ((await page.locator('body').textContent()) || '').replace(/\s+/g, ' ');

  expect(horizonsText).not.toContain('Black Ledger');
  expect(horizonsText).not.toContain('Open Black Ledger');
  expect(horizonsText).toContain('Early campaign work stays behind the main app');
  expect(horizonsText).toContain('Not the front door');
  expect(horizonsText).not.toContain('Watch');
  expect(horizonsText).not.toContain('deep dive');

  const llmsResponse = await request.get(`${baseUrl}/llms.txt`);
  expect(llmsResponse.ok()).toBeTruthy();
  const llmsText = await llmsResponse.text();
  expect(llmsText).not.toContain('/ledger :');
  expect(llmsText).not.toContain('/black-ledger');
  expect(llmsText).not.toContain('Black Ledger');
  expect(llmsText).not.toContain('/alice');
  expect(llmsText).not.toContain('/table-pulse');
  expect(llmsText).not.toContain('/quicksilver');
  expect(llmsText).not.toContain('/local-co-processor');

  const aiResponse = await request.get(`${baseUrl}/ai.txt`);
  expect(aiResponse.ok()).toBeTruthy();
  const aiText = await aiResponse.text();
  expect(aiText).not.toContain('/alice');
  expect(aiText).not.toContain('/table-pulse');
  expect(aiText).not.toContain('/quicksilver');
  expect(aiText).not.toContain('/local-co-processor');
  expect(aiText).not.toContain('AI helper');

  const sitemapResponse = await request.get(`${baseUrl}/sitemap.xml`);
  expect(sitemapResponse.ok()).toBeTruthy();
  const sitemapText = await sitemapResponse.text();
  expect(sitemapText).not.toContain('/ledger');
  expect(sitemapText).not.toContain('/alice');

  const robotsResponse = await request.get(`${baseUrl}/robots.txt?public-route-guard=1`);
  expect(robotsResponse.ok()).toBeTruthy();
  const robotsText = await robotsResponse.text();
  for (const path of ['/alice', '/ledger', '/participate', '/table-pulse', '/quicksilver', '/local-co-processor', '/karma-forge']) {
    expect(robotsText).toContain(`Disallow: ${path}`);
  }
});

test('downloads concierge reads like instant support, not internal governance', async ({ page }) => {
  await page.goto(`${baseUrl}/downloads/concierge`, { waitUntil: 'domcontentloaded' });
  const bodyText = ((await page.locator('body').textContent()) || '').replace(/\s+/g, ' ');

  expect(bodyText).toContain('Answer first. Show the path. Fix or report.');
  for (const term of [
    'Wrapper status',
    'Proof',
    'receipt',
    'bounded handoff',
    'first-party boundary',
    'mint',
    'booking',
    'setup clinic',
    'help session',
    'call',
    'Lunacal',
  ]) {
    expect(bodyText, `/downloads/concierge should not expose "${term}"`).not.toContain(term);
  }
});
