*

!.dockerignore

**/.git/
**/.env
**/.env.*
**/.state/
**/bin/
**/obj/
**/node_modules/
**/Docker/Secrets/
**/*.key
**/*.p12
**/*.pem
**/*.pfx
**/credentials*.json
**/credentials*.yml
**/credentials*.yaml
**/secrets*.json
**/secrets*.yml
**/secrets*.yaml
