#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
from pathlib import Path

from absolute_completion_common import now_iso, read_yaml, write_json
from verify_public_routes_from_manifest import DEFAULT_OUTPUT, DEFAULT_MANIFEST, load_hub_live_audit_module


FORBIDDEN_STRINGS = (
    "device-code auth",
    "worker host",
    "fleet",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run a live public-surface audit against chummer.run.")
    parser.add_argument("--base-url", required=True, help="Public base URL, for example https://chummer.run")
    parser.add_argument("--manifest", default=str(DEFAULT_MANIFEST), help="Path to PUBLIC_LANDING_MANIFEST.yaml")
    parser.add_argument(
        "--route-proof",
        default=str(DEFAULT_OUTPUT),
        help="Path to an existing route proof JSON packet generated by verify_public_routes_from_manifest.py",
    )
    parser.add_argument(
        "--output",
        default="",
        help="Optional output path for the live public surface audit packet",
    )
    return parser.parse_args()


def fetch_text(fetch, base_url: str, path: str) -> tuple[int, str]:
    status, body, _, _ = fetch(base_url, path, follow_redirects=True)
    if isinstance(body, bytes):
        return status, body.decode("utf-8", errors="replace")
    return status, str(body)


def main() -> int:
    args = parse_args()
    manifest = read_yaml(Path(args.manifest))
    route_proof = Path(args.route_proof)
    audit = load_hub_live_audit_module()

    status_code, landing_html = fetch_text(audit.fetch, args.base_url, "/")
    ctas = []
    for cta in manifest.get("hero_ctas") or []:
        href = str(cta.get("href") or "").strip()
        label = str(cta.get("label") or "").strip()
        if not href or not label:
            continue
        pattern = re.escape(href)
        present = re.search(pattern, landing_html) is not None and re.search(re.escape(label), landing_html, re.IGNORECASE) is not None
        ctas.append({"label": label, "href": href, "present": present})

    forbidden_hits = [token for token in FORBIDDEN_STRINGS if token.lower() in landing_html.lower()]
    payload = {
        "contract_name": "chummer.live_public_surface_audit",
        "generated_at_utc": now_iso(),
        "base_url": args.base_url,
        "landing_status_code": status_code,
        "route_proof_path": str(route_proof),
        "route_proof_present": route_proof.is_file(),
        "hero_ctas": ctas,
        "forbidden_string_hits": forbidden_hits,
        "status": "pass" if status_code == 200 and all(cta["present"] for cta in ctas) and not forbidden_hits and route_proof.is_file() else "fail",
    }

    if args.output:
        write_json(Path(args.output), payload)

    if payload["status"] != "pass":
        raise SystemExit(
            "live_public_surface_audit failed: "
            f"status_code={status_code} ctas_ok={all(cta['present'] for cta in ctas)} forbidden_hits={forbidden_hits} route_proof_present={route_proof.is_file()}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
